### ISSUE TITLE
When i click Config icon my app screen becomes black and cant revert that

### ISSUE THREAD

**Issue by jmpena** [inspireui/fluxbuilder#1]
When i click the "configuration icon" next to app design, the app screen becomes black and there is no way to revert that

**Comment by talalibdah** [comment]
Open app settings in the simulator and uncheck dark mode.

**Comment by minhcasi** [comment]
@jmpena @talalibdah 

Please update the latest stable versions: 
+ Window OS: select the link https://github.com/inspireui/fluxbuilder/releases/download/1.0.0/FluxBuilder.1.0.zip
+ macOS: download from Appstore https://apps.apple.com/vn/app/fluxbuilder/id1500753204?mt=12
+ iPad/iPhone: download from Appstore https://apps.apple.com/tt/app/fluxbuilder-pro/id1503282735?ign-mpt=uo%3D2
+ tablet/android: download from Google Play https://play.google.com/store/apps/details?id=com.inspireui.fluxbuilderpro&hl=en
