### ISSUE TITLE
image cache is not enabled

### ISSUE THREAD

**Issue by mohamedibrahim89** [inspireui/fluxbuilder#100]
I make all steps in this https://docs.inspireui.com/fluxstore/performance/
but my app take time to load image and product can u help me in this

<img width="1440" alt="Screen Shot 2020-05-28 at 5 49 23 PM" src="https://user-images.githubusercontent.com/35544603/83163649-91242a00-a10b-11ea-81b5-36249f7a76ea.png">

**Comment by minhcasi** [comment]
Duplicate of #94

**Comment by iqmtgar** [comment]
Can you help me solve a images problem?
