### ISSUE TITLE
The image cache is not enabled error.

### ISSUE THREAD

**Issue by wordinvestor** [inspireui/fluxbuilder#101]
Hello, I have rtl urdu language website. When i try to Analyse connection then it give error that The image cache is not enabled , i installed regenerate thumbnail plugin too. Also it give some other errors too on app screen. Please check attached file.
My site url is https://spiritualhope.net/
![test](https://user-images.githubusercontent.com/911892/83248224-2c75d780-a1be-11ea-9bf3-a741257c14d0.png)

**Comment by wordinvestor** [comment]
This blue screen error problem is in latest version 1.0.5 . I just checked older version 1.0.4 and it is working fine even with error of the image cache is not enabled.

**Comment by wordinvestor** [comment]
Hello, 
Is there any progress on this issue?
Regards

**Comment by vumanhsn97** [comment]
@wordinvestor 
This is bug. It has been fixed in next version(1.0.6)
Thanks!

**Comment by kweyamba** [comment]
@vumanhsn97  where can we download the new version. Its not there in the downloads section.

**Comment by vumanhsn97** [comment]
@kweyamba 
Please download latest version: https://github.com/inspireui/fluxbuilder/releases
