### ISSUE TITLE
FluxBuilder - Please activate our purchase code before

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/fluxbuilder#102]
I get this message when trying to click the save icon on this app.  I have no idea where you got activate this. I already activated the plug on my site.
<img width="366" alt="Screen Shot 2020-05-29 at 11 47 24 PM" src="https://user-images.githubusercontent.com/66133967/83284568-06c0f080-a207-11ea-84ef-b1399f4d166e.png">

**Comment by deep12650** [comment]
I am also having the same error "Please activate your code before". Please suggest!

**Comment by dragooninasia** [comment]
not sure why but when I go back to work on customizing all my changes i made is not longer there and reverted back to the default sample content

**Comment by minhcasi** [comment]
@dragooninasia - pls help to raise your all comment to one ticket #110

**Comment by asifashi1** [comment]
I am also facing this issue. Anyone find the solution?
