### ISSUE TITLE
FluxBuilder - Magic Tool issue

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/fluxbuilder#103]
Error when check flutter ! Please try again!
The Path of project should not be empty

<img width="721" alt="Screen Shot 2020-05-30 at 12 24 21 AM" src="https://user-images.githubusercontent.com/66133967/83287684-45a57500-a20c-11ea-9407-d6abe967cb61.png">

**Comment by mrfoxie** [comment]
the same issue is with me also

**Comment by minhcasi** [comment]
this issue is fixed on `1.0.6` - thank you!
