### ISSUE TITLE
Issue : replace the category with your own category ID (this ID can get when editting from the category in admin site):

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/fluxbuilder#104]
I have no idea what this ID category ID is.  I checked google and couldn't find any any help with this.

**Comment by dragooninasia** [comment]
<img width="738" alt="Screen Shot 2020-05-30 at 12 34 25 AM" src="https://user-images.githubusercontent.com/66133967/83288446-8d78cc00-a20d-11ea-8b4b-f25bddfe2265.png">

**Comment by wordinvestor** [comment]
Go to categories section in wordpress, mouse hover on edit button under any category name and you can see it at bottom of page. Check attached image.
![id](https://user-images.githubusercontent.com/911892/83290657-67006400-a200-11ea-9e08-25b30452663a.png)
or click on edit button under any category so you will also be able to see cat id in address bar like /co.uk/wp-admin/term.php?taxonomy=product_cat&tag_ID=**27**&post_type=product&wp_http_referer

**Comment by dragooninasia** [comment]
Thank you very much
