### ISSUE TITLE
WCFM - Issue with "Stores" don't populate

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/fluxbuilder#105]
<img width="372" alt="Screen Shot 2020-05-30 at 1 31 47 AM" src="https://user-images.githubusercontent.com/66133967/83293108-7a69fa00-a215-11ea-9ed0-a01159157709.png">

The stores are not populating on the Stores tab as shown in this screenshot.  Help please.

**Comment by minhcasi** [comment]
@dragooninasia - pls help to raise your all comment to one ticket #110
