### ISSUE TITLE
Lost the data I put 3 times now using the Flux Builder to fill in About Us Tab

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/fluxbuilder#106]
I have entered and filled the data on the About us tab of the Flux Builder and it no longer there.  It reverted back to the default content but the picture i changed on it is still there.  This is frustrating.
<img width="1188" alt="Screen Shot 2020-05-30 at 1 59 10 AM" src="https://user-images.githubusercontent.com/66133967/83295601-6fb16400-a219-11ea-8b17-0f6eeeed9618.png">

**Comment by minhcasi** [comment]
@dragooninasia - pls help to raise your all comment to one ticket #110
