### ISSUE TITLE
How do you change the logo on the login page

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/fluxbuilder#107]
<img width="390" alt="Screen Shot 2020-05-30 at 2 16 05 AM" src="https://user-images.githubusercontent.com/66133967/83297225-607fe580-a21c-11ea-96f8-0a4ffaba4312.png">

**Comment by minhcasi** [comment]
@dragooninasia - this is missing config, we will upgrade it on `1.0.6` - thanks

**Comment by minhcasi** [comment]
@dragooninasia - pls help to raise your all comment to one ticket #110
