### ISSUE TITLE
Changing the loading icon in Flux Builder

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/fluxbuilder#108]
How do you change the loading icon on the app?
<img width="127" alt="Screen Shot 2020-05-30 at 11 24 03 AM" src="https://user-images.githubusercontent.com/66133967/83319395-5552a700-a268-11ea-88cc-07c3c2666944.png">

**Comment by minhcasi** [comment]
this feature is not available, we will investigate and upgrade it later - thank you!

**Comment by minhcasi** [comment]
you could open the app to change as manually config :)
