### ISSUE TITLE
"This widget could not be previewed...." Issue

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/fluxbuilder#109]
<img width="356" alt="Screen Shot 2020-05-30 at 4 45 47 PM" src="https://user-images.githubusercontent.com/66133967/83325270-40d8d380-a295-11ea-818b-a9830d4d0178.png">

**Comment by minhcasi** [comment]
Fixed on the latest release - thank you!

<img width="1182" alt="Screen Shot 2020-06-04 at 09 56 56" src="https://user-images.githubusercontent.com/1459805/83709914-ba801100-a649-11ea-86fd-9ddf3ba945a9.png">
