### ISSUE TITLE
fluxbulider in windows 10 issuie 

### ISSUE THREAD

**Issue by thawadi** [inspireui/fluxbuilder#11]
I tested the fluxbulider in Windows 10 when I insert the purchase code it can’t be copied ctrl+v I entered manually the code and it says it is not correct

**Comment by minhcasi** [comment]
@thawadi - we will fix the purchase code issue on the next release - thank you!

**Comment by thawadi** [comment]
when the new release will be available

**Comment by paradisecy** [comment]
> I tested the fluxbulider in Windows 10 when I insert the purchase code it can’t be copied ctrl+v I entered manually the code and it says it is not correct

i have the same issue

**Comment by minhcasi** [comment]
@thawadi @paradisecy - the copy and past on Window is having an issue with the core of library we are using, pls move to this ticket for further conversation and update #16
