### ISSUE TITLE
SDK not found

### ISSUE THREAD

**Issue by mrfoxie** [inspireui/fluxbuilder#111]
![Untitled](https://user-images.githubusercontent.com/25217451/83349287-54e20b00-a351-11ea-8732-742d044c8835.png)
unable to add flutter SDK in-app while its work fine in android studio
![Untitled](https://user-images.githubusercontent.com/25217451/83349308-865ad680-a351-11ea-91e7-0089694b7177.png)

**Comment by dragooninasia** [comment]
I had the same issue but when I went through to published and replaced the en_config.json file with the code that it spits out at publish.
 BUt then I got this once i installed a test run on my mobile phone and got the RED OF DEATH screen.
![IMG_1800](https://user-images.githubusercontent.com/66133967/83661031-c63ee980-a5ef-11ea-9c35-0c9f641962b9.PNG)

When I email them with the issue, Minh just tells me

 "We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible."

I'm not sure how difficult it is to get them to reply every day on the github support.  Makes no sense to me.

**Comment by dragooninasia** [comment]
I ended up learning .dart and using XD for UI and using flutter directly instead of this incomplete fluxbuilder.  I would recommend the same.  Better to have a product you understand and can customize.  Coding really isn't that hard it seems.  Learning to us Python as well for web applications full stack

**Comment by dragooninasia** [comment]
I plan on asking for a refund if they don't start actually fix their digital product.

**Comment by minhcasi** [comment]
@mrfoxie - the magic tool will be fix on next `1.0.6` - thank you!

**Comment by mrfoxie** [comment]
@minhcasi I will be waiting thank you

**Comment by minhcasi** [comment]
There is an issue on Window that could not run the flutter automatically via a script, we will hide the Magic Tool on next `1.0.6` to do more investigate and update

In the meantime please help to install Flutter manually - https://flutter.dev/docs/get-started/install

**Comment by mrfoxie** [comment]
is flutter is been removed from 1.0.6 build
