### ISSUE TITLE
left side menu ( “drawer layout ”) need webview 

### ISSUE THREAD

**Issue by nadeemkhan085** [inspireui/fluxbuilder#113]
hello 
i want some customization like how to achieve? 
*****i need support for leftside menu** ****
[menu and tabbar file.zip](https://github.com/inspireui/fluxbuilder/files/4734031/menu.and.tabbar.file.zip)
[menu and tabbar file.zip](https://github.com/inspireui/fluxbuilder/files/4734037/menu.and.tabbar.file.zip)

*
 1- left side menu… how to rename shop (to shop rename) Blog (to blog rename) and change wordpress icon
 2- categories always expend.. 
3- can i show categories by id on left menu( “drawer layout ”) ?
 4- adding about us  (actually webview) to left side menu ( “drawer layout ”)
================================================================
******for right menu 
5- where to find privacy and terms (need to put url)
================================================================
to change app dark mode color
 6- Can i change dark mode color? means can i use #2874f0 ?
================================================================
**** i notice my app showing product everything working good... but when its comes to thumbnail its not showing image.... product page showing image ........but home page not showing image.... i am using cloudinary for image
================================================================
menu.dart
tabbar.dart attached already 
thank you in advance

**Comment by nadeemkhan085** [comment]
hello 
any suggestion ?

**Comment by minhcasi** [comment]
@nadeemkhan085 - We wanted to thank you for your patience during this busy time. We currently have reduced staff and a significantly higher volume of inquiries. We’re working as hard as we can to get to your request as soon as possible.

@vumanhsn97 - pls help with investigating

**Comment by nadeemkhan085** [comment]
hello..
i know you guys are busy... but its not good to keeping on hold for many days....opened ticket 7 days now. only at start support was good

**Comment by vumanhsn97** [comment]
1 -To change this: https://tppr.me/6BHnA. You need to edit code in drawer header: https://tppr.me/PMVFH
2 - Follow this issue: https://github.com/inspireui/support/issues/3671#issuecomment-643042029
3 - You need to edit code in showCategories function: https://tppr.me/5vHFt
4 - Use this code: https://tppr.me/hxAGg. Change url to your about us page
5 - Privacy use page id, not url: https://tppr.me/9Ij0h. You can see in settings.dart file
6 - You can update dark color in styles.dart file common folder

**Comment by nadeemkhan085** [comment]
good day @vumanhsn97 @minhcasi 
thank you for your reply 
i am using fluxstore MV
really if i know the coding i will never ask for support....i wasted days on github and google but cant find solution.
 you need to provide documentation or guide by coding 

1- solved 
2- .. solved
**3- can i show categories by id on left menu( “drawer layout ”) ?  important
4- adding  webview to left side menu ( “drawer layout ”) important**
5-  solved
6- solved

**Comment by vumanhsn97** [comment]
3 - replace showCategories function
4 - replace case 'about': https://tppr.me/rp7qB
Compare in this file: 
[menu.dart.zip](https://github.com/inspireui/fluxbuilder/files/4769240/menu.dart.zip)

**Comment by nadeemkhan085** [comment]
hello @vumanhsn97  thank you for your reply from very busy time.
4- i  edit  'about' menu.dart there was no error but still its not showing in leftside menu  not showing still please check if i miss anything 
here is the changes i made.......... can you check what i am doing wrong

`import 'dart:async';

import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'widgets/common/webview.dart';
import 'package:provider/provider.dart';

import 'common/config.dart';
import 'common/constants.dart';
import 'common/tools.dart';
import 'generated/l10n.dart';
import 'models/app.dart';
import 'models/category/category.dart';
import 'models/category/category_model.dart';
import 'models/product/product.dart';
import 'models/user/user_model.dart';

class MenuBar extends StatefulWidget {
  final GlobalKey<NavigatorState> navigation;
  final StreamController<String> controllerRouteWeb;

  MenuBar({this.navigation, this.controllerRouteWeb});

  @override
  _MenuBarState createState() => _MenuBarState();
}

class _MenuBarState extends State<MenuBar> {
  Widget imageContainer(String link) {
    if (link.contains('http://') || link.contains('https://')) {
      return Image.network(
        link,
        fit: BoxFit.cover,
      );
    }
    return Image.asset(
      link,
      fit: BoxFit.cover,
    );
  }

  Widget drawerItem(item) {
    final isTablet = Tools.isTablet(MediaQuery.of(context));
    kLayoutWeb = (kIsWeb || isTablet);

    if (item['show'] == false) return Container();
    switch (item['type']) {
      case 'home':
        {
          return ListTile(
            leading: const Icon(
              Icons.shopping_basket,
              size: 20,
            ),
            title: Text(S.of(context).shop),
            onTap: () {
              if (kLayoutWeb) {
                widget.controllerRouteWeb.sink.add("/home-screen");
              } else {
                if (Navigator.canPop(context)) {
                  Navigator.pop(context);
                } else {
                  Navigator.of(context).pushReplacementNamed("/home-screen");
                }
              }
            },
          );
        }
      case 'web':
        {
          return Column(
            children: [
              if (kLayoutWeb)
                ListTile(
                  leading: const Icon(
                    Icons.list,
                    size: 20,
                  ),
                  title: Text(S.of(context).category),
                  onTap: () {
                    widget.controllerRouteWeb.sink.add("/category");
                  },
                ),
              if (kLayoutWeb)
                ListTile(
                  leading: const Icon(
                    Icons.search,
                    size: 20,
                  ),
                  title: Text(S.of(context).search),
                  onTap: () {
                    widget.controllerRouteWeb.sink.add("/search");
                  },
                ),
              if (kLayoutWeb)
                ListTile(
                  leading: const Icon(Icons.settings, size: 20),
                  title: Text(S.of(context).settings),
                  onTap: () {
                    if (kLayoutWeb) {
                      widget.controllerRouteWeb.sink.add("/setting");
                    } else {
                      Navigator.of(context).pushNamed("/setting");
                    }
                  },
                )
            ],
          );
        }
      case 'about':
        {
          return ListTile(
            leading: const Icon(
              Icons.info_outline,
              size: 20,
            ),
            title: Text(S.of(context).aboutUs),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => WebView(
                    url: "https://inspireui.com/about", //your about us url
                    title: S.of(context).webView,
                  ),
                ),
              );
            },
          );
        }
      case 'blog':
        {
          return ListTile(
            leading: const Icon(FontAwesomeIcons.wordpress, size: 20),
            title: Text(S.of(context).blog),
            onTap: () {
              if (kLayoutWeb) {
                widget.controllerRouteWeb.sink.add("/blogs");
              } else {
                Navigator.of(context).pushNamed("/blogs");
              }
            },
          );
        }
      case 'login':
        {
          bool loggedIn = Provider.of<UserModel>(context).loggedIn;
          return ListTile(
            leading: Icon(Icons.exit_to_app, size: 20),
            title: loggedIn
                ? Text(S.of(context).logout)
                : Text(S.of(context).login),
            onTap: () {
              if (loggedIn) {
                Provider.of<UserModel>(context, listen: false).logout();
              } else {
                if (kLayoutWeb) {
                  widget.controllerRouteWeb.sink.add("/login");
                } else {
                  Navigator.pushNamed(context, "/login");
                }
              }
            },
          );
        }
      case 'category':
        {
          return Column(
            children: [
              SizedBox(
                height: 20,
              ),
              ExpansionTile(
                initiallyExpanded: true,
                title: Text(
                  S.of(context).byCategory.toUpperCase(),
                  style: TextStyle(
                    fontSize: 14,
                    fontWeight: FontWeight.w600,
                    color: Theme.of(context).accentColor.withOpacity(0.5),
                  ),
                ),
                children: showCategories(),
              )
            ],
          );
        }
      default:
        return Container();
    }
  }

  @override
  Widget build(BuildContext context) {
    printLog("[MenuBar] build");
    Map<String, dynamic> drawer =
        Provider.of<AppModel>(context, listen: false).drawer ?? kDefaultDrawer;

    return SingleChildScrollView(
      key: drawer['key'] != null ? Key(drawer['key']) : null,
      child: Column(
        children: <Widget>[
          DrawerHeader(
            padding: EdgeInsets.all(0),
            child: Stack(
              children: [
                if (drawer['background'] != null)
                  Container(
                    child: imageContainer(drawer['background']),
                  ),
                if (drawer['logo'] != null)
                  Align(
                    alignment: Alignment(-0.8, 0.6),
                    child: Container(
                      height: 38,
                      child: imageContainer(drawer['logo']),
                    ),
                  )
              ],
            ),
          ),
          Padding(
            padding: const EdgeInsets.only(left: 15.0),
            child: Column(
              children: List.generate(drawer['items'].length, (index) {
                return drawerItem(drawer['items'][index]);
              }),
            ),
          )
        ],
      ),
    );
  }

  List showCategories() {
    final categories = Provider.of<CategoryModel>(context).categories;
    List<Widget> widgets = [];

    if (categories != null) {
      var list = categories.where((item) => item.parent == '0').toList();
      for (var index in list) {
        widgets.add(
          ExpansionTile(
            title: Padding(
              padding: const EdgeInsets.only(left: 0.0, top: 0),
              child: Text(
                index.name.toUpperCase(),
                style: TextStyle(fontSize: 14),
              ),
            ),
            children: getChildren(categories, index),
          ),
        );
      }
    }
    return widgets;
  }

  List getChildren(List<Category> categories, Category category) {
    List<Widget> list = [];
    var children = categories.where((o) => o.parent == category.id).toList();

    if (children.isEmpty) {
      list.add(
        ListTile(
          leading: Padding(
            child: Text(S.of(context).seeAll),
            padding: const EdgeInsets.only(left: 20),
          ),
          trailing: const Icon(
            Icons.arrow_forward_ios,
            size: 12,
          ),
          onTap: () {
            Product.showList(
                context: context, cateId: category.id, cateName: category.name);
          },
        ),
      );
    }
    for (var i in children) {
      list.add(
        ListTile(
          leading: Padding(
            child: Text(i.name),
            padding: const EdgeInsets.only(left: 20),
          ),
          trailing: const Icon(
            Icons.arrow_forward_ios,
            size: 12,
          ),
          onTap: () {
            Product.showList(context: context, cateId: i.id, cateName: i.name);
          },
        ),
      );
    }
    return list;
  }
}
`

**Comment by nadeemkhan085** [comment]
hello 
maybe your not getting me 
actually i want to **add some web link (webview and post screen) in left side menu and right side menu** 
please help 
i am stuck same place now 10 days
thank you

**Comment by vumanhsn97** [comment]
Add this line {"type": "about", "show": true} in lib/common/config/general.dart https://tppr.me/zobUO
