### ISSUE TITLE
Don't have an account? Sign up

### ISSUE THREAD

**Issue by dragooninasia** [inspireui/fluxbuilder#114]
where do i go to change the link to the "Sign up"  from the login menu?
<img width="244" alt="Screen Shot 2020-06-06 at 5 26 08 AM" src="https://user-images.githubusercontent.com/66133967/83927208-71010480-a7b6-11ea-9846-bdd827d36d4c.png">

**Comment by minhcasi** [comment]
Do you mean to change the link to another Link or something else? Pls explain?
