### ISSUE TITLE
Save my work in fluxbuilder !!!

### ISSUE THREAD

**Issue by imartichauhan** [inspireui/fluxbuilder#115]
Hey how can i save work or designs in fluxbuilder. everytime i close the app, all data/history deletes. pls assist me

**Comment by minhcasi** [comment]
@imartichauhan - thank you for reporting, we suspect this could is a bug, the team will investigate and keep new update - very best

@vumanhsn97

**Comment by vumanhsn97** [comment]
@imartichauhan 
You active your site and press this button: https://tppr.me/8IJZ0 to save in server
