### ISSUE TITLE
Error windows fluxbuilder

### ISSUE THREAD

**Issue by Marcleiton** [inspireui/fluxbuilder#116]
Hello, my fluxbuilder finds an error, follows all settings and to no avail.
https://imgur.com/a/CH9Js18

I can't change the editor's language, can't see as images, can't see the products.

Could you help me?

**Comment by minhcasi** [comment]
@Marcleiton - this could be the issue when integrating with your site, could you mind to share the detail info from your website so that we could have a check

**Comment by Marcleiton** [comment]
> @Marcleiton - esse pode ser o problema ao se integrar ao seu site. Você pode compartilhar as informações detalhadas do seu site para que possamos verificar

hi, how to send private message here.

**Comment by minhcasi** [comment]
@Marcleiton - you could send via this form http://verify.inspireui.com/ - thank you!

**Comment by vumanhsn97** [comment]
@Marcleiton 
Change language in your app preview to Arabic.
https://tppr.me/BpTqQ
Can't get products with English language: https://tppr.me/4It7Z but it's working well in Arabic language: https://tppr.me/l7Mss

**Comment by Marcleiton** [comment]
Hello, but my language is Brazilian Portuguese, did I change it at the time of publication?

**Comment by vumanhsn97** [comment]
@Marcleiton 
Checked it. Your site just get data fail in English language. Other language is working well
