### ISSUE TITLE
Fluxbuilder Shopify linking

### ISSUE THREAD

**Issue by StarboyB** [inspireui/fluxbuilder#119]
Hi there, I've loaded my data from my Shopify as in the video tutorials on Youtube. I manage to get my categories populated but when it comes to my blogs I get this error.
![image](https://user-images.githubusercontent.com/66732791/84269494-92048500-ab29-11ea-8818-e243d86055ae.png)
My About page doesn't link up either.
Trying to enable dark mode on the emulator in Fluxbuilder doesn't work either.

**Comment by AbimaelASilva** [comment]
Good Morning.

You asked me to view this topic but my problem is not this with FluxBuilder.

In my case, the images appear, however when I insert my key to activate and click on confirm, I am asked:

"please field your email and your name"

 but I do not see any field where I must inform this data.

**Comment by minhcasi** [comment]
This issue is fixed on latest Fluxbuilder and Fluxstore Shopify - let us know your checking - thank you!
