### ISSUE TITLE
 image cache not enabled 

### ISSUE THREAD

**Issue by ritutechno** [inspireui/fluxbuilder#120]
hi this is the first time I purchase your product I try to build my first app I have small problem
in flux builder image cache not enabled how can I solve this because image load so slow.

![Screenshot_5](https://user-images.githubusercontent.com/43493593/84253593-c24e2280-ab2d-11ea-8a8a-9d7a3cb37732.png)

i have already install  WP REST API plugin. 
but it's show me ame error in fluxbuilder. so please help me what i do...??
![Screenshot_6](https://user-images.githubusercontent.com/43493593/84253315-697e8a00-ab2d-11ea-8d7f-113cdda8fae9.png)

please fix it.

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help with investigating

**Comment by vumanhsn97** [comment]
@ritutechno 
Can you send your site and woocommerce key to vumanhsn97@gmail.com?

**Comment by ritutechno** [comment]
hello, 

i send you details via email.

**Comment by ritutechno** [comment]
Hello,

Any update on this?

Thanks & Regrades-

Ritu Techno
Mob.- 946263501, 9982264200
E-mail- info@ritutechno.com
web- www.ritutechno.com

**Comment by vumanhsn97** [comment]
@ritutechno 
Login in your site and press this button. Please waiting for loading successful. https://tppr.me/3fGl6
