### ISSUE TITLE
Plugin regenarate Thumbnails is not installed 

### ISSUE THREAD

**Issue by bigbossmaher** [inspireui/fluxbuilder#123]
![image](https://user-images.githubusercontent.com/15154710/84488392-052c0980-ac98-11ea-80c4-3bc070229306.png)

i got this error on fluxbuilder hower the plugin is already installed

![image](https://user-images.githubusercontent.com/15154710/84488473-25f45f00-ac98-11ea-842c-13a381fe3f0d.png)

**Comment by minhcasi** [comment]
@bigbossmaher - this could be a bug on latest 1.0.5 - we will fix it on 1.0.6 - thank you!

**Comment by bigbossmaher** [comment]
@minhcasi , even the cashing us enabled , my app still loading too slow , can you please check it is slow or it in normal ?
https://play.google.com/store/apps/details?id=com.shop.cheap

**Comment by Arshadlive** [comment]
Hi, I'm getting the same issue, I have done everything according to the guide, Still it's showing "The Image cache is not enable. Please let me know how to solve this issue. Thanks

**Comment by bigbossmaher** [comment]
> @minhcasi , even the cashing us enabled , my app still loading too slow , can you please check it is slow or it in normal ?
> https://play.google.com/store/apps/details?id=com.shop.cheap

still wating for your answer

**Comment by vumanhsn97** [comment]
@bigbossmaher 
It is normal. But when you scroll to bottom to get more data of New Collection, it will be slow because your data saved in ram too large. We fixed it in next version by using ListView.builder
With plugin regenerate thumbnail is not installed. Can you submit the form to http://verify.inspireui.com/
Thanks!

**Comment by ddanas** [comment]
Have the same issue with regenerate thumbnails plugin. When will v1.0.6 be released?

Thanks

**Comment by vumanhsn97** [comment]
@ddanas 
Please download latest version: https://github.com/inspireui/fluxbuilder/releases

**Comment by ddanas** [comment]
Ok regeneerate plugin issue solved by installing new version
