### ISSUE TITLE
Unable to connect to my magento store in flexbuilder pro app on my iphone

### ISSUE THREAD

**Issue by hardikcool2000** [inspireui/fluxbuilder#124]
Provided site url and access token, it is not connecting to API

Quick help would be appritiated

**Comment by minhcasi** [comment]
@hardikcool2000 - could you help to share the screenshot of the issue- thank you!

**Comment by hardikcool2000** [comment]
[cid:195C696F-C700-45DC-A18D-EBD9A37D686C-L0-001]
Hardik Trivedi
CEO & Solution Architect
OM INFOSOLUTIONS Inc.

On 15-Jun-2020, at 6:03 PM, Minh Pham <notifications@github.com> wrote:

﻿

@hardikcool2000<https://github.com/hardikcool2000> - could you help to share the screenshot of the issue- thank you!

**Comment by minhcasi** [comment]
@hardikcool2000 - sorry i've missed this ticket - pls help to resend the config and screenshot issue, we could not get it from your previous comment - thank you!

**Comment by AbimaelASilva** [comment]
Good Morning, @minhcasi 

You criticized me because I created a topic identical to an existing one, and asked to follow the resolution of the problem at this address, but I don't see any comment that shows the resolution of the problem.

"Images are not loaded into the app".

**Comment by minhcasi** [comment]
@AbimaelASilva - 
Sorry, i could not get your point about the criticized issue as could not see your previous comment or detail explain on this ticket. 

The validates image caching is still open issue on this ticket - https://github.com/inspireui/fluxbuilder/issues/144
