### ISSUE TITLE
Add to cart and product variation not working

### ISSUE THREAD

**Issue by darkcoder217** [inspireui/fluxbuilder#126]
I am trying the free fluxstore app on windows before buying the plugin,so as i am testing it the data from my woocommerce is being fetched properly but i am not able to add anything to my cart and also the variation for my products is not available just the number of products is visible, please help me with these 2 issues rest everything is working great,installed all plugin from the documentation, i am using this theme https://themeforest.net/item/shopkeeper-ecommerce-wp-theme-for-woocommerce/9553045

**Comment by minhcasi** [comment]
@darkcoder217 - there is 2 features from the Fluxbuilder may not work completely is the Checkout + Login

As we design for Preview App only (login feature will be conflict with the Fluxbuilder app user) - we will think about how to improve it later

**Comment by darkcoder217** [comment]
I am not talking about checkout + login , i am not able to add anything in my cart and my product variations are not visible inside the product page
