### ISSUE TITLE
 fluxbuilder  doesn't just show all categories from my wocommerce site.

### ISSUE THREAD

**Issue by imbluee** [inspireui/fluxbuilder#128]
hi there ,
i config my Woocommerce site to fluxbuilder via rest API and it had been connect successfully.

but the problem is fluxbuilder not fetching all categories just showing some of them..
FluxStore version :  FluxStore-woo 1.7.5 .
fluxbuilde version  : v.1.0.5.

please help ..

**Comment by imbluee** [comment]
hi ..
any help ??

**Comment by minhcasi** [comment]
@imbluee - sorry for late response - would you help to share the screenshot of the issue and the config info website URL/consumes key... so that we could check the root cause (you could try to send private via http://verify.inspireui.com) - thank you!

**Comment by imbluee** [comment]
HI dear,
i add all screenshot which you request and send them via  ((  http://verify.inspireui.com )).
i have 22 categories which just showing 9 categories ((categiries.jpj).

**Comment by imbluee** [comment]
is that way you support us ?
i waiting for about 5 days ...

**Comment by minhcasi** [comment]
@imbluee - sorry for late response, we are working hard to update new release 1.0.6

@vumanhsn97 - pls help to check this issue

**Comment by vumanhsn97** [comment]
@imbluee 
Please download latest version: https://github.com/inspireui/fluxbuilder/releases

**Comment by imbluee** [comment]
Hello there ,
i donload and install version 1.0.6 fluxbuider ,
but still didnt fetching  my each of categoreis ..
![set API](https://user-images.githubusercontent.com/19878860/85926800-9c08e080-b8aa-11ea-97ed-562b4d46f034.JPG)
![MIstore Api](https://user-images.githubusercontent.com/19878860/85926803-9d3a0d80-b8aa-11ea-8364-a8675c835cc2.JPG)
![mY categories on admin panel](https://user-images.githubusercontent.com/19878860/85926804-9dd2a400-b8aa-11ea-95de-a9fe813a777e.JPG)
![not showing categories](https://user-images.githubusercontent.com/19878860/85926806-9e6b3a80-b8aa-11ea-8c40-e90a5c8f35a3.JPG)

**Comment by vumanhsn97** [comment]
@imbluee 
Item count in your category need to greater than 0. https://tppr.me/9OeII
