### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by heftipascal1** [inspireui/fluxbuilder#129]
Hi, in the Fluxbuilder when i woudl add a item Category then the Error Message is 

![Unbenannt](https://user-images.githubusercontent.com/67189625/85199930-9b44dd00-b2f3-11ea-8b0a-8125bb65acfb.JPG)
![Unbenannt](https://user-images.githubusercontent.com/67189625/85199939-b1eb3400-b2f3-11ea-8c1d-2d13d304722f.JPG)
and the analysis connection is all enabled and connected. 

How we can fix this? That we can add categories?

**Comment by vumanhsn97** [comment]
@heftipascal1 
Please download latest version: https://github.com/inspireui/fluxbuilder/releases

**Comment by heftipascal1** [comment]
Hi, i have testet it, but it doesn´t works also with the new version
