### ISSUE TITLE
Fluxbuilder "VCRUNETIME140_1.dll was not found"

### ISSUE THREAD

**Issue by bidfor** [inspireui/fluxbuilder#13]
I have installed the vc_redist.x64.exe and i still getting this error "VCRUNETIME140_1.dll was not found" when i run it on Windows 10. 

![image](https://user-images.githubusercontent.com/2523772/78521407-52a17b80-77fc-11ea-89d4-2441187c4473.png)

**Comment by minhcasi** [comment]
@bidfor - please help check solution on #14
