### ISSUE TITLE
Registration Fail

### ISSUE THREAD

**Issue by golira** [inspireui/fluxbuilder#131]
I could not register an account at registration page.. it show errors "Exception : No route was found matching the URL and request method"

**Comment by minhcasi** [comment]
@golira - sorry the Fluxbuilder is not allowed to create the account or project checkout, it is used for the design UI purpose - thank you!

**Comment by golira** [comment]
@minhcasi  hi there, it was.. as i already done one apps project with fluxbuilder and it does support registration checkout those.. but when i came to another new project it shows this error
