### ISSUE TITLE
Please field your email && your app name

### ISSUE THREAD

**Issue by seyitacar** [inspireui/fluxbuilder#132]
I am trying to activate my license but I get the same error on Mstore Api wordpress plugin and FluxBuilder

string(52) “{error field your email && your app name”}” The purchase code is incorrect.

![image](https://user-images.githubusercontent.com/14896676/85724722-26abdd00-b6fd-11ea-9f3b-aa0e54481f72.png)
![image](https://user-images.githubusercontent.com/14896676/85724823-40e5bb00-b6fd-11ea-9670-8457e4acc5f6.png)

**Comment by vumanhsn97** [comment]
@seyitacar 
Please download latest version: https://github.com/inspireui/fluxbuilder/releases
