### ISSUE TITLE
Please field your email && your app name

### ISSUE THREAD

**Issue by macololiv** [inspireui/fluxbuilder#133]
when i try to active the multivendor in flux builder i got this message  ...  Please field your email && your app name ...and i cant save the process
![issue](https://user-images.githubusercontent.com/67354221/85816503-24637600-b731-11ea-92aa-6a8c83b5dacd.jpg)

**Comment by vumanhsn97** [comment]
@macololiv 
Please download latest version: https://github.com/inspireui/fluxbuilder/releases
