### ISSUE TITLE
FluxStore Woocommerce Errors - Multiple Errors

### ISSUE THREAD

**Issue by pmop9654** [inspireui/fluxbuilder#134]
Hello there,

Facing couple of issues;

1. Unable to validate purchase code in Inspire UI wordpress plugin, notifies its incorrect purchase code
2. Regenerate Thumbnail plugin is activated, still it shows the error on site connection
3. When try to activate license in FluxBuilder I am getting error: "Please field your email && your app name"
4. Woocommerce categories not showing

Can you guys please help with this ?

Thank you!

**Comment by minhcasi** [comment]
@pmop9654 - would you mind to share the detail website infor so that we could help for checking - could submit private to http://verify.inspireui.com - thank you!

**Comment by vumanhsn97** [comment]
@pmop9654 
Please download latest version: https://github.com/inspireui/fluxbuilder/releases
