### ISSUE TITLE
MSstore api on wordpress causes error on wordpress and causes error on getting data from app

### ISSUE THREAD

**Issue by maynard88** [inspireui/fluxbuilder#135]
This is the error I am getting if MSTORE API is activated but when deactivated the error is gone. Please fix

Notice: register_rest_route was called incorrectly. Namespace must not start or end with a slash. Please see Debugging in WordPress for more information. (This message was added in version 5.4.2.) in /home/ikumpra/public_html/wp-includes/functions.php on line 5167

**Comment by maynard88** [comment]
I fixed it myself but you guys need to update your source control

FlutterUser.php line 7
 $this->namespace     = '/api/flutter_user';  

You have slash on your "/api"


another issue

mstore-api.php line 151
 register_rest_route( 'order', '/verify',

You have no / pn verify parameter

kindly update your plugin. Thank you.

**Comment by minhcasi** [comment]
fixed on latest plugin - thank you!
