### ISSUE TITLE
Category and Product Fetching Issue

### ISSUE THREAD

**Issue by asifashi1** [inspireui/fluxbuilder#136]
On Main Page there quite differences in product fetching. 
1. Banner Images fetching limited products from the Shopify collection and sometimes didn't find any product.
2. Nothing showing New Arrival & Best Selling section in Android Studio
3. Mian sticky logo not working properly
![Screenshot_2](https://user-images.githubusercontent.com/40563557/85917130-b1f5b180-b868-11ea-83b2-5bce41d4116b.png)
![Screenshot_3](https://user-images.githubusercontent.com/40563557/85917131-b3bf7500-b868-11ea-8be5-4f9fc4cf1482.png)
![Screenshot_4](https://user-images.githubusercontent.com/40563557/85917133-b3bf7500-b868-11ea-9b4e-facd64e1c828.png)

**Comment by minhcasi** [comment]
@asifashi1 - pls help us to post your all comments to the same ticket #136 - that will help us to focus easily on the issues and have more space for other user ticket support - thank you for your time

**Comment by asifashi1** [comment]
From the Category section, just two of my collections get the some of the products, and the rest of the categories are empty. I also want to show limited custom categories in category option. 
![Screenshot_5](https://user-images.githubusercontent.com/40563557/85918968-64814080-b878-11ea-94ca-97f4ae4918ae.png)

**Comment by asifashi1** [comment]
1. I want to change the Default Currency and Symble USD to AED
2.  Where can I edit the Live chat and Whatapp chat option under the profile section? I also want to show the chat option on every page.
3. From where I can change the Icon, Splash Screen, Logo, App Icon,

**Comment by asifashi1** [comment]
How can we increase the character of the product title

**Comment by asifashi1** [comment]
I have build APK along with all Bugs. There also login issue
![WhatsApp Image 2020-06-27 at 2 24 04 PM](https://user-images.githubusercontent.com/40563557/85920142-4d475080-b882-11ea-80e3-0158e01688e9.jpeg)

**Comment by asifashi1** [comment]
**Here are other issues.
1. White space between Products Row
2. Duplicate Product Title and Default Title
3. Automatically product in cart which product click for view
4.  Review not working properly
5. Product Additional Information section not working
6. Menu Item Character, not show full Title**
![Screenshot_7](https://user-images.githubusercontent.com/40563557/85920454-f5f6af80-b884-11ea-942a-b88b520ed973.png)
![Screenshot_8](https://user-images.githubusercontent.com/40563557/85920455-f727dc80-b884-11ea-87b6-f56d3d0ca94f.png)
![Screenshot_9](https://user-images.githubusercontent.com/40563557/85920456-f727dc80-b884-11ea-8066-de9bc5ab4384.png)
![Screenshot_10](https://user-images.githubusercontent.com/40563557/85920457-f7c07300-b884-11ea-8a21-a22a3a79ebf2.png)
![Screenshot_11](https://user-images.githubusercontent.com/40563557/85920458-f7c07300-b884-11ea-9b2e-d415953a159b.png)

**Comment by asifashi1** [comment]
iOS Building Issue.
![Screenshot_12](https://user-images.githubusercontent.com/40563557/85920490-4b32c100-b885-11ea-85a1-da145049ca55.png)

**Comment by minhcasi** [comment]
@asifashi1 - did you have a chance to test with the latest fluxbuilder `1.0.6` ? Our team is working hard on the product to update it more stable. If you are felling a waste of time on the product, it is ok to process the refund to save it - thank you!

Please note that you could not build the ios on the window, ios only could be built on Mac OS

**Comment by asifashi1** [comment]
Ok, I am going to download and test the new fulxbuilder version.
Ok First let me build Android then I will arrange Mac OS and then build iOS app
Note: My concern does not belong to a refund. I need long term solution for my project and after long research, I have found you and I was disappointed due to delay in support response.

**Comment by asifashi1** [comment]
I have built the layout with updated fluxbuilder and still things the same.
Missing the New Arrival and Best Selling section in Android Studio
![Screenshot_9](https://user-images.githubusercontent.com/40563557/85999014-96330c80-ba1c-11ea-9dd4-13e8fddf3c6e.png)
Note: I am using latest Android Studio Version

**Comment by asifashi1** [comment]
1. In Vertical Device mode when I scroll the down with mouse wheel one of collection page automatically open.
2. On collection page when I scroll mouse up its add product in the cart automatically
![Screenshot_10](https://user-images.githubusercontent.com/40563557/85999769-b6170000-ba1d-11ea-9693-0146e8ca1734.png)
3. On home screen slider, and banner link fetches product when I run a test and after some time it does not fetch any products from all collection from slider and banner.
![Screenshot_11](https://user-images.githubusercontent.com/40563557/86000117-26258600-ba1e-11ea-9185-4b8e7659b208.png)
