### ISSUE TITLE
Category Section Not Getting Products

### ISSUE THREAD

**Issue by asifashi1** [inspireui/fluxbuilder#137]
From the Category section, just two of my collections get the some of product and rest of categories are empty
![Screenshot_5](https://user-images.githubusercontent.com/40563557/85917276-c2f2f280-b869-11ea-88fe-627c542121aa.png)

**Comment by minhcasi** [comment]
@asifashi1 - pls help us to post your all comments to the same ticket #136 - that will help us to focus easy on the issues and have more space for other user ticket support - thank you for your time
