### ISSUE TITLE
How Change Default Currency and Symbol

### ISSUE THREAD

**Issue by asifashi1** [inspireui/fluxbuilder#138]
I want to change my app default currency and symbol USD to AED
![Screenshot_6](https://user-images.githubusercontent.com/40563557/85917311-1c5b2180-b86a-11ea-96ea-006c6c07263d.png)

**Comment by minhcasi** [comment]
@asifashi1 - pls help us to post your all comments to the same ticket #136 - that will help us to focus easy on the issues and have more space for other user ticket support - thank you for your time
