### ISSUE TITLE
Live Chat & Whatsapp Option Hidden

### ISSUE THREAD

**Issue by asifashi1** [inspireui/fluxbuilder#139]
In the FluxBuilder here is the communication section under the profile section but there is no icon and option in Android Studio. Where I can show the chat option and I also want to show only WhatsApp and Facebook chat option and the rest of option want to hide.
Is That Possible to show these options in the whole app frame instead of the profile section?
![Screenshot_7](https://user-images.githubusercontent.com/40563557/85917401-e10d2280-b86a-11ea-9f8e-d36f5511ab3e.png)

**Comment by minhcasi** [comment]
@asifashi1 - pls help us to post your all comments to the same ticket #136 - that will help us to focus easy on the issues and have more space for other user ticket support - thank you for your time
