### ISSUE TITLE
Fluxbuilder not running on Windows 10

### ISSUE THREAD

**Issue by kurkuteabhi** [inspireui/fluxbuilder#14]
Tried to run Fluxbuilder very first time. requesting you to give setup guide for same. please refer image below

![Annotation 2020-04-06 164701](https://user-images.githubusercontent.com/43174699/78553156-724d9980-7826-11ea-9629-0fe9a5fdfa8b.jpg)
![purches](https://user-images.githubusercontent.com/43174699/78553164-75488a00-7826-11ea-8d2e-3c1e8738132f.jpg)

**Comment by shah0203** [comment]
![image](https://user-images.githubusercontent.com/63024624/78578876-cceff100-7838-11ea-82db-2b0842c836ed.png)


even i was getting the same error but when i install the above Microsoft Visual C ++ packages it resolved my issue.

**Comment by minhcasi** [comment]
@kurkuteabhi - please try the vc_redist.x64.exe and restart the window will fix the issue

https://github.com/inspireui/fluxbuilder/releases/download/1.0.0/vc_redist.x64.exe

**Comment by kurkuteabhi** [comment]
T


> 
> 
> ![image](https://user-images.githubusercontent.com/63024624/78578876-cceff100-7838-11ea-82db-2b0842c836ed.png)
> 
> even i was getting the same error but when i install the above Microsoft Visual C ++ packages it resolved my issue.

Thanks 

> 
> 
> @kurkuteabhi - please try the vc_redist.x64.exe and restart the window will fix the issue
> 
> https://github.com/inspireui/fluxbuilder/releases/download/1.0.0/vc_redist.x64.exe

Thanks
