### ISSUE TITLE
The image cache is not enabled 

### ISSUE THREAD

**Issue by Arshadlive** [inspireui/fluxbuilder#140]
**I have correctly activated the Regenerated plugin and renerate all the media file according to the documentation, Still I am getting an issue like this** 

![image](https://user-images.githubusercontent.com/66934543/85918697-ab743380-b882-11ea-8b04-ccd03178f8c0.png)

**Actually i have 241 images in my media folder (in my website) but in the fluxbuilder it showing 20 images and those 20 images are not cached.** 

![image](https://user-images.githubusercontent.com/66934543/85918763-26d5e500-b883-11ea-8680-152dd79f7ffc.png)

Looking for a solution for this.

**Comment by Arshadlive** [comment]
How long does it takes to solve this issue? Does this is a bug in Flux builder?

**Comment by vumanhsn97** [comment]
@Arshadlive 
Can you send your config.dart to vumanhsn97@gmail.com?

**Comment by Arshadlive** [comment]
Hello, I am using Flux builder Tool, Not Android Studio. Can I do it with
Flux builder?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by vumanhsn97** [comment]
You can send me your consume key, consume secret, website url

**Comment by Arshadlive** [comment]
Okay,

Website URL -  https://frango.lk/

*Consumer key - *ck_41b85d5e76d421d7255ed2a032e607b23835b456

*secret - *cs_b407da4690bdffcb8508a64d06ffe64d543fb2b3

Waiting for your reply. Thanks.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by vumanhsn97** [comment]
@Arshadlive 
In your site, regenerate thumbnails is not working or you don't press regenerate button and waiting for progress finish.
You can check with image in your site by:
imageurl/nameimage.png become imageurl/nameimage-medium.png
Example: 
https://mstore.io/wp-content/uploads/2015/08/image1xxl-91.jpg
become
https://mstore.io/wp-content/uploads/2015/08/image1xxl-91-medium.jpg

**Comment by Arshadlive** [comment]
Hi, I have activated correctly and Regenerate the thumbnail and i waited to
complete (Check the screenshot below)

[image: image.png]


* This is my website Credential Can you able to check it please? *
User name - Shafras

Pass - &bPm&6ZWxg$tULYl0%qLPMZE

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Arshadlive** [comment]
Please let me know, How to solve this problem. I will be waiting for your
reply. Thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by talalibdah** [comment]
Hello. I'm facing the same issue as well on https://www.derbi.app

**Comment by talalibdah** [comment]
Any update on this issue guys? I'm still facing it even though I generated the thumbnails correctly.

**Comment by minhcasi** [comment]
This issue is fixed on the latest `1.0.7` - we will release it on next week - thanks

**Comment by minhcasi** [comment]
Fixed on latest https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
