### ISSUE TITLE
fetch categoreis Issue

### ISSUE THREAD

**Issue by imbluee** [inspireui/fluxbuilder#141]
Hello there ,
i download and install version 1.0.6 fluxbuider ,
but still didnt fetching my each of categoreis ..

![set API](https://user-images.githubusercontent.com/19878860/85926882-146fa180-b8ab-11ea-8043-4f6255223df1.JPG)
![MIstore Api](https://user-images.githubusercontent.com/19878860/85926885-15a0ce80-b8ab-11ea-9c99-ca6975df8c5f.JPG)
![mY categories on admin panel](https://user-images.githubusercontent.com/19878860/85926886-15a0ce80-b8ab-11ea-9021-0869107a3839.JPG)
![not showing categories](https://user-images.githubusercontent.com/19878860/85926887-16396500-b8ab-11ea-9c00-08bade181f8a.JPG)

**Comment by minhcasi** [comment]
@imbluee - could I know if you are using latest `mstore-api` plugin? Thank you!
