### ISSUE TITLE
chekout keep loading 

### ISSUE THREAD

**Issue by macololiv** [inspireui/fluxbuilder#142]
Hello when i try to proceed to the checkout in the app in  flexbuilder the loading icon keep loading  and never go the the checkout page 
![Screenshot 2020-06-28 17 14 10](https://user-images.githubusercontent.com/67354221/85959790-10538a80-b964-11ea-9706-975231e1d602.png)

thank you

**Comment by minhcasi** [comment]
@macololiv - the checkout will not work on the Preview - pls try with the Read device (ios or android) - thank you!

**Comment by macololiv** [comment]
It was working in the previous version of FluxBuilder but now and even in iPad it open a pop up with the website checkout 
![FB790535-A350-4608-A51B-A153BF932CBD](https://user-images.githubusercontent.com/67354221/86035736-6d9e1900-ba02-11ea-81fa-55ea2f7a0e4a.png)

**Comment by macololiv** [comment]
the app  is still going to my website checkout page not  the app checkout page even in android studio therefore looks and act like a progresive app not a native or even a hybrid also when i click on the home button in the bottom of the phone take me to may website home page not to the app home page 
![android](https://user-images.githubusercontent.com/67354221/86182940-8687f680-baf6-11ea-9063-591832260596.jpg)

**Comment by minhcasi** [comment]
@macololiv - the webview payment is the feature to support process via Webview:
<img width="953" alt="Screen Shot 2020-07-02 at 10 02 10" src="https://user-images.githubusercontent.com/1459805/86311671-1a6ad700-bc4b-11ea-8589-a37e9a073604.png">

Current the app only support some native payment like Paypal, Tap
