### ISSUE TITLE
I do not want some categories to appear in the application. How can I close them?

### ISSUE THREAD

**Issue by roseyazilim** [inspireui/fluxbuilder#147]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: I do not want some categories to appear in the application. How can I close them?
+ Product & version:  Fluxstore PRo opencart
+ Flutter (or React Native) version: -
+ Testing Device/Simulator: -
+ Screenshot issues (drag the file to attach here): -

How do I prevent some categories on the site from appearing?

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

sent

**Comment by roseyazilim** [comment]
Hello,
I didn't want to open a new support, should I open it?
I do not register through the application I use opencart

**Comment by minhcasi** [comment]
@roseyazilim - the fluxbuilder is not supported with the Login or Payment - you could try this feature on real fluxstore app or the simulator - thanks
