### ISSUE TITLE
FluxBuilder Not Show Categories of Dokan Multivendor website

### ISSUE THREAD

**Issue by sanpiseth** [inspireui/fluxbuilder#148]
I downloaded a fluxbuilder version 1.0.6 to connect to my dokan multivendor website, and all my categories are not shown.
The fluxbuilder shows other categories that are not mine.

**Comment by minhcasi** [comment]
Thank you for the feedback, could you help so share the screenshot issue.

Please help us to submit this form and fill all required info to continue with the support  - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by sanpiseth** [comment]
I cannot open the http://verify.inspireui.com/ 
please provide other link.
The problem is Fluxbuilder does not have my category data of my website (using Dokan)

**Comment by minhcasi** [comment]
@sanpiseth - it's verified via email - could you help to share the detailed screenshot of this issue - thank you!

**Comment by sanpiseth** [comment]
Hello,

I just re-open it to screenshot it for you. Luckily i see it is working :D

Therefore, i will close this ticket

**Comment by sanpiseth** [comment]
I re-open it and i notice it is working normal. Therefore, I will this ticket.
