### ISSUE TITLE
My google sheets are not working with fluxbuilder.

### ISSUE THREAD

**Issue by tripsman** [inspireui/fluxbuilder#149]
I made a replica of the demo Google sheet. When I entered my google sheet **ID** im getting this error. https://prnt.sc/tdp76m .
What are the steps to make the API work and how do I connect it to the Flutter app?
![Screen Shot 2020-07-07 at 6 34 10 PM](https://user-images.githubusercontent.com/8105277/86914455-65269c00-c0ee-11ea-899d-6d05b6467078.png)

**Comment by minhcasi** [comment]
@tripsman - you could try to publish as web - https://support.google.com/docs/answer/183965?co=GENIE.Platform%3DDesktop&hl=en
