### ISSUE TITLE
FluxBuilder VALIDATION Failed

### ISSUE THREAD

**Issue by shah0203** [inspireui/fluxbuilder#15]
Hi,

When i copy the REST API keys from my website and paste it under FluxBuilder it is not validating and getting failed with the error message "code. woocommerce_rest_authentication_error" "Message. Invalid signature. Provided signature dose not match". 

I am stuck here, your prompt response will be highly appreciated.

**Comment by shah0203** [comment]
![API-ERROR](https://user-images.githubusercontent.com/63024624/78576105-e68f3980-7834-11ea-964a-58f8a3278e0d.png)

**Comment by minhcasi** [comment]
@shah0203 - could you check the consumer/secret keys is correct? Please also check this guide https://docs.woocommerce.com/document/woocommerce-rest-api/

**Comment by shah0203** [comment]
@minhcasi ..thanks dear as you said i rechecked the keys it was wrongly copied ,thus i re enter it again and it got validated now.

But after doing changes on FluxBuilder and copying the config file to config_en.json it is not taking effect in 'Android Studio' mobile emulator. can you share any docs or video to cutomize APP on Flux Builder and replicate it to Android Studio for building APK.

**Comment by minhcasi** [comment]
@shah0203 - would you mind to share the website / keys and the config.json here - I will make the video demo to clarify more detail that could be useful

**Comment by shah0203** [comment]
Hi,

Thanks for the response. i have been trying and got fixed it through your online docs and videos.
________________________________
