### ISSUE TITLE
fluxbuilder not work on window os

### ISSUE THREAD

**Issue by Cheewingtan** [inspireui/fluxbuilder#151]
![WhatsApp Image 2020-07-09 at 12 39 29 PM](https://user-images.githubusercontent.com/11556877/86997739-5ff64980-c1e1-11ea-84c1-14fb30cce4b8.jpeg)
is just keep loading and loading ,it doesn't appear the design screen, but on mac version is work fine to me

**Comment by jurbanoa** [comment]
Hola no me permite activar el producto y menos guardar el que ya tengo activado.

![image](https://user-images.githubusercontent.com/67361627/87102455-93ec6180-c217-11ea-8d2a-c78c7ef1c392.png)

**Comment by jurbanoa** [comment]
![image](https://user-images.githubusercontent.com/67361627/87102500-bed6b580-c217-11ea-9887-92da1259bbd3.png)

**Comment by minhcasi** [comment]
@Cheewingtan - pls try to update to latest `1.0.6` and the activate feature will work - thank you!

**Comment by Cheewingtan** [comment]
> @Cheewingtan - pls try to update to latest `1.0.6` and the activate feature will work - thank you!

1.06 same error to me , it keeps loading and I can't design the screen

**Comment by Cheewingtan** [comment]
> @Cheewingtan - pls try to update to latest `1.0.6` and the activate feature will work - thank you!

And my issue is not about the activate problem, is design page can't display it always keep loading on window os ,can you please take a look???

**Comment by Cheewingtan** [comment]
![WhatsApp Image 2020-07-10 at 11 36 59 AM](https://user-images.githubusercontent.com/11556877/87113911-e5d9c980-c2a1-11ea-8951-c426e81c7ca7.jpeg)


> @Cheewingtan - pls try to update to latest `1.0.6` and the activate feature will work - thank you!
![WhatsApp Image 2020-07-10 at 11 36 59 AM](https://user-images.githubusercontent.com/11556877/87113923-ef633180-c2a1-11ea-8418-f66350d6eade.jpeg)
Please take a look

**Comment by ssathamenterprises** [comment]
> > @Cheewingtan - pls try to update to latest `1.0.6` and the activate feature will work - thank you!
> 
> And my issue is not about the activate problem, is design page can't display it always keep loading on window os ,can you please take a look???

same issue for me also

**Comment by Cheewingtan** [comment]
> @Cheewingtan - pls try to update to latest `1.0.6` and the activate feature will work - thank you!

hi how the issue?

**Comment by minhcasi** [comment]
@vumanhsn97 - pls suggest on this issue

**Comment by minhcasi** [comment]
@Cheewingtan - we have tried to install the build from https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.6 - and it is working fine

Would you mind to reinstall the app and restart again - or try to register with new user email to see if can be fix?

Also share your detail website consume keys so that we could have a check

**Comment by Cheewingtan** [comment]
> @Cheewingtan - we have tried to install the build from https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.6 - and it is working fine
> 
> Would you mind to reinstall the app and restart again - or try to register with new user email to see if can be fix?
> 
> Also share your detail website consume keys so that we could have a check

ok I reinstall again and work to me now ,thanks

**Comment by Cheewingtan** [comment]
> @Cheewingtan - we have tried to install the build from https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.6 - and it is working fine
> 
> Would you mind to reinstall the app and restart again - or try to register with new user email to see if can be fix?
> 
> Also share your detail website consume keys so that we could have a check

is haven't loading anymore, but I cant upload images why? and didn't get the product info from my website API,(on mac os everything fine !) I using Multi vendor woo-commerce , can you try on this one ? because other customers still facing the same issue with this 
![Screenshot (37)](https://user-images.githubusercontent.com/11556877/87514051-3b501500-c6ac-11ea-968a-0d4a38895ac7.png)

**Comment by Cheewingtan** [comment]
@minhcasi

**Comment by ssathamenterprises** [comment]
Now works for me thanks

**Comment by ssathamenterprises** [comment]
works

**Comment by Cheewingtan** [comment]
> works

what you have done before ? I'm still not working ,I can't upload any image on multi-vendor

**Comment by ssathamenterprises** [comment]
some time works some time loading

**Comment by minhcasi** [comment]
Fixed on latest release https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
