### ISSUE TITLE
Error en agregar imagen para categoría

### ISSUE THREAD

**Issue by jurbanoa** [inspireui/fluxbuilder#152]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version: Fluxstore Pro & 1.7.5
+ Flutter (or React Native) version: Fluxstore Pro
+ Testing Device/Simulator:  www.diwora.com
+ Screenshot issues (drag the file to attach here): 

![image](https://user-images.githubusercontent.com/67361627/87008589-9acc9300-c189-11ea-8fe6-ff947ecc8698.png)

![image](https://user-images.githubusercontent.com/67361627/87008212-05c99a00-c189-11ea-985d-2062451e6500.png)

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- We will close the ticket if missing the proof of purchase on step 2. The screenshot purchase attaches here will be invalid.
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

**Comment by minhcasi** [comment]
@jurbanoa - try to update to latest release `1.0.6` - thank you!

**Comment by maxileft** [comment]
<img width="461" alt="Screen Shot 2020-07-16 at 9 50 50 PM" src="https://user-images.githubusercontent.com/1119206/87686878-3de76300-c7af-11ea-8618-9ef466c68a33.png">
i have the same problem, can not add or update icon image, im using latest 1.0.6 version.
