### ISSUE TITLE
fluxbuilder not works in my laptop 

### ISSUE THREAD

**Issue by ssathamenterprises** [inspireui/fluxbuilder#153]
fluxbuider not works in laptop when i use the api and product code not works in my laptop ( my mobile works but cant upload categories images ) keep loading not shows anything

**Comment by minhcasi** [comment]
@ssathamenterprises @emanuelecolella @nucl123 - could you share the screenshot of the issues? Thank you!

**Comment by nucl123** [comment]
> @ssathamenterprises @emanuelecolella @nucl123 - could you share the screenshot of the issues? Thank you!

https://github.com/inspireui/support/issues/4099
