### ISSUE TITLE
Fluxnews 1.4.1 + Fluxbuilder does not work

### ISSUE THREAD

**Issue by realmultimedia** [inspireui/fluxbuilder#156]
Dear team, 

Since I've bought the source, I have never been able to make it look (functionality wise) like the demo.
It is not working.

Source unpacked -> copy/paste from fluxbuilder into config_en.json -> run the simulator -> app starts and hangs with blank screen. Unacceptable. 
As soon as I drag the source into Android Studio (4.0.1) - Get dependencies notice keeps coming up and it doesn't go away. 
Flutter doctor: 0 issues. (as if I open the WooCommerce source it works like charm) so there is definitely something wrong with this 1.4.1 version of the Fluxnews

**Comment by minhcasi** [comment]
@realmultimedia - pls try to clean up the cache from fluxnews project to see if it works fine? https://gist.github.com/minhcasi/2362b8ed369738cea2bf10a57ac569e1

**Comment by realmultimedia** [comment]
Hi, 
Unfortunately, it doesn't help.

It stops working when I copy/paste the code from fluxbuilder. 

<img width="1440" alt="Screenshot 2020-07-15 at 07 51 37" src="https://user-images.githubusercontent.com/68022923/87513122-18a00b00-c670-11ea-9b59-644d7b649c85.png">
 
<img width="1440" alt="Screenshot 2020-07-15 at 07 49 32" src="https://user-images.githubusercontent.com/68022923/87512926-c65eea00-c66f-11ea-84e9-0056986e06fa.png">
<img width="1440" alt="Screenshot 2020-07-15 at 07 48 33" src="https://user-images.githubusercontent.com/68022923/87512940-cb239e00-c66f-11ea-826b-3fa8f4adc0bc.png">
<img width="1440" alt="Screenshot 2020-07-15 at 07 50 21" src="https://user-images.githubusercontent.com/68022923/87512978-db3b7d80-c66f-11ea-9696-89aa0b709520.png">

**Comment by realmultimedia** [comment]
Problem - Fluxbuilder issue
ISSUE: "SplashScreen" type - "static" or "zoomIn" not supported
Solution: USE "animated" only
