### ISSUE TITLE
Flux builder is not recorgnizing our payment gateway

### ISSUE THREAD

**Issue by Dinokojt** [inspireui/fluxbuilder#157]
1. Hi we have been login in on the builder API but we see that the payment gateway is not working at all can you kindly help us. see (paymentgateway.PNG)

2. We also see the bottom overflow error which we think is affecting our image sliders from loading we not sure. see (bottomoverflow.PNG )

https://izinto.co.za/wp-login.php?redirect_to=https%3A%2F%2Fizinto.co.za%2Fwp-admin%2Fpost.php%3Fpost%3D46393%26action%3Dedit&reauth=1

![;ayment gateway problem](https://user-images.githubusercontent.com/65246387/87477214-0e5a1e80-c628-11ea-96db-114ef04e53b1.PNG)
![bottom overflow](https://user-images.githubusercontent.com/65246387/87477222-10bc7880-c628-11ea-9479-eb1bfe2a831c.PNG)

**Comment by vumanhsn97** [comment]
@Dinokojt 
Please download latest version(1.0.6) https://tppr.me/n0cMJ

**Comment by Dinokojt** [comment]
Hi,

I'm using windows.

Regards

*TIISETSO DINOKO*

Cell: *081 489 2861*

**Comment by vumanhsn97** [comment]
@Dinokojt 
It is available on windows os: https://github.com/inspireui/fluxbuilder/releases
