### ISSUE TITLE
Use FluxBuilder build the theme not works continuously in the app

### ISSUE THREAD

**Issue by ssathamenterprises** [inspireui/fluxbuilder#158]
Hello I have issues with the app .json When I upload my .json in Wordpress it’s accept.

After I install my app and check the home page works what I edited in .json

Then once I close the app and open again totally the theme goes to default

Then I try uninstall and install the app it’s works ( but when I close the app and open again it’s goes default theme )

Note ( .json I use FluxBuilder) What is the issue
+ Product & version: fluxstore multi vendor use dokan
Thank you so much for your time 😊

**Comment by minhcasi** [comment]
Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission.
 Thank you for your time!

**Comment by ssathamenterprises** [comment]
![A04CE8E9-8C06-444E-A9B0-2C78F6580901](https://user-images.githubusercontent.com/68118999/87749768-2bf7d580-c82c-11ea-8a7a-7d0500c23d15.jpeg)
![Uploading F4C93B86-A825-483C-BA4F-11AC6937CE21.jpeg…]()

**Comment by ssathamenterprises** [comment]
I submit the proof above the screenshots please check it thanks

**Comment by minhcasi** [comment]
@vumanhsn97 - pls help with suggestion

**Comment by vumanhsn97** [comment]
@ssathamenterprises 
This bug come from flutter cache
You need to remove app in your devices and run this cmd:
flutter clean
flutter run

**Comment by ssathamenterprises** [comment]
Once I uploaded in play store and Apple store, I need to change the home page from Wordpress ( upload json ) 

Then How to I run command ?

**Comment by vumanhsn97** [comment]
@ssathamenterprises 
Your app is available in play store and you want to change theme app from Wordpress site. When you download and install your app, it is working well. But when you close and open it again, it is fail to get new theme. Is it your issue?
Can you share your app link in play store?

**Comment by ssathamenterprises** [comment]
Yes you are the right this is my issue.

Please check the app here 

https://drive.google.com/file/d/1o3l07ZJGYhmR5twoPS7B-wzN9m-I2jkF/view?usp=drivesdk

Because I change my app for few days works with ionic once this issue solved I will upload again

**Comment by vumanhsn97** [comment]
@ssathamenterprises
Can't install with this apk file. Please run this cmd and share your output release folder
flutter build apk --split-per-abi

**Comment by ssathamenterprises** [comment]
Ok

**Comment by ssathamenterprises** [comment]
Please try this I use your  command 

https://drive.google.com/file/d/1fSueucBlkpnoR0Gd8x8_bXGvDs624spJ/view?usp=drivesdk

**Comment by vumanhsn97** [comment]
@ssathamenterprises 
Same. I can't install it

**Comment by ssathamenterprises** [comment]
But my mobiles can install ok give me some time I send you

**Comment by ssathamenterprises** [comment]
@vumanhsn97 

there is three apk which one you need

**Comment by ssathamenterprises** [comment]
https://drive.google.com/file/d/1dQOxUd5UTKEsAKzu-Mv-aGkiT5dxRx58/view?usp=sharing

here is the output

**Comment by ssathamenterprises** [comment]
i solved my self (i remove all config_xx.json  except config_en.json)
