### ISSUE TITLE
Can't upload any new image on Flux Builder on Windows 10

### ISSUE THREAD

**Issue by itlakshmanan** [inspireui/fluxbuilder#159]
Can't able upload any new image for Logo, Banner or Category icon on Flux Builder on Windows 10. If I upload any image loader keeps on loading endlessly. I'm using v1.0.6. 

I have been suffering from last 15 days with this issue on Flux Builder. Kindly give a solution for this.

**Comment by minhcasi** [comment]
@itlakshmanan - thank you for reporting - we will investigate and let you know

**Comment by mbmendiola** [comment]
Good day.

I am facing the same issue as well. Do you already have fix for this?

Looking forward to your response.

**Comment by itlakshmanan** [comment]
@minhcasi I'm waiting for a long time for this fix. Could tell me when we can expect a release?

**Comment by minhcasi** [comment]
@itlakshmanan - we have fixed this issue on latest `1.0.7` - it will be ready on next week - thank you!

**Comment by minhcasi** [comment]
Fixed on latest release https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
