### ISSUE TITLE
Issue with FluxBuilder windows

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/fluxbuilder#16]
it has some serious issue.

Copy paste does not work, I mean I can not paste my domain in domain area.

Basically, CTRL+C and CTRL + V is not working anywhere. I can not paste domain, nor license key.

Also, the changes I made in data/design are not being saved. Every time I need to start everything from new whenever I start this software.

Also once i publish the app, it does not allow me to select and copy the code and other side the copy button does not work too. whenever i click on copy, it does not copy anything.

**Comment by kurkuteabhi** [comment]
I am facing same issue with copy past. please check attachement

![47b496fd9b9](https://user-images.githubusercontent.com/43174699/78661257-0df50d80-78ec-11ea-84ce-81a1f6d1bfd0.gif)

**Comment by kurkuteabhi** [comment]
Facing same issue with copy past, plz check attachment

![cf18eb8a5ca](https://user-images.githubusercontent.com/43174699/78661430-65937900-78ec-11ea-8e0f-79639d21122d.gif)

**Comment by thawadi** [comment]
Yes I face same proplem

**Comment by minhcasi** [comment]
There are known issues on the latest Window version of the Fluxbuilder - we are investigating the solution and will update shortly !

@dttrung26

**Comment by minhcasi** [comment]
We keep following this ticket from the LIbrary core - https://github.com/flutter/flutter/issues/54226

**Comment by HarrySmith01** [comment]
Also please do not forget below one:

`the changes I made in data/design are not being saved. Every time I need to start everything from new whenever I start this software.`

**Comment by minhcasi** [comment]
please try this version to fix the copy/paste issue - https://github.com/inspireui/fluxbuilder/releases/download/latest/FluxBuilder_windowOS.zip - thanks

**Comment by HarrySmith01** [comment]
> `the changes I made in data/design are not being saved. Every time I need to start everything from new whenever I start this software.`

any solution on this?
