### ISSUE TITLE
FluxBuilder Won't let you change the settings drawer of fluxstore

### ISSUE THREAD

**Issue by jsone1909** [inspireui/fluxbuilder#162]
When changing the design for FluxStore (Woocommerce version) you are not able to make changes to the settings drawer. I delete the Fluxstore logo and upload a new one as well as a background image and also enable or disable blog, home, login link and after saving the app doesn't actually save. It reverts back to the default. 

I brought this to the developers attention via code canyon comments over a month ago and I was told that the 1.06 release would fix it and it didn't.

Now when I try to upload a logo or background image to the same section it stalls out and the progress image is stuck on the screen. Still not able to save anything.

Also, there is additional padding on the front screen between different modules. This was also supposed to be fixed with this update.

![image](https://user-images.githubusercontent.com/68604979/88075692-002b6700-cb2e-11ea-8efb-5574efa49e80.png)

**Comment by AJOnlineServices** [comment]
Having the same issue and still no update for a fix.

**Comment by minhcasi** [comment]
Fixed on latest release https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
