### ISSUE TITLE
Only one product shows in app

### ISSUE THREAD

**Issue by smartcomp007** [inspireui/fluxbuilder#163]
Hello i have issue when connecting with my site all sections shows correct ,but just shows one product
https://prnt.sc/tmfw0c
Categories integrated all but no products,site is woocommerce smartcomp.am
please help to fix that

**Comment by minhcasi** [comment]
@smartcomp007 - could you share the detail config to http://verify.inspireui.com/ - we will help to have a check

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
