### ISSUE TITLE
Problem using fluxbulider 

### ISSUE THREAD

**Issue by emadpost2016** [inspireui/fluxbuilder#164]
**_Step 1 (require): describe detail issues & screenshots_**
+ Detail Issues: 
+ Product & version:
+ Flutter (or React Native) version: 
+ Testing Device/Simulator: 
+ Screenshot issues (drag the file to attach here): 

**_Step 2 (require): submit proof of purchasing the license on http://verify.inspireui.com_**

**_Important Note:_**
- Please help to ready the support policies before creating a new ticket: https://inspireui.com/support-policies/
- Kindly create only *One Ticket* & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but want to create a new ticket, just do simple step by linking to the previous verified ID (you don't need to submit the form again), for example, #Ticket-ID

Thank you so much for your time 😊

![image](https://user-images.githubusercontent.com/58606378/88380807-89000800-cda5-11ea-8ff2-88caf4b369bf.png)
![image](https://user-images.githubusercontent.com/58606378/88380844-96b58d80-cda5-11ea-9cd5-edc3a14e9b9d.png)
![image](https://user-images.githubusercontent.com/58606378/88380869-a339e600-cda5-11ea-9f59-4bb29bb6dfa8.png)

When trying to add new products to the main page of the application, the sections that exist on the site do not appear and the original application sections appear, knowing that all sections and sections have been linked from the site, but when adding new ones on the main page it does not appear, please solve

1.7.4
1.17.3
samsung A30

**Comment by minhcasi** [comment]
noted with investigating - thank you!

**Comment by emadpost2016** [comment]
any update

**Comment by emadpost2016** [comment]
Any update

**Comment by minhcasi** [comment]
This issue is fixed on latest 1.0.7 - thank you!

**Comment by emadpost2016** [comment]
Where is version 1.0.7

**Comment by emadpost2016** [comment]
any update

**Comment by minhcasi** [comment]
Please download on this link https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
