### ISSUE TITLE
problems with FLUXSTORE

### ISSUE THREAD

**Issue by luisalf23** [inspireui/fluxbuilder#166]
I made the complete settings of the site and opened the application but at the moment of entering the purchase code, it hangs and does nothing.

what should I do ?

![Captura de Pantalla 2020-07-25 a la(s) 10 23 09 p  m](https://user-images.githubusercontent.com/68795380/88471179-813a8380-cecb-11ea-8de3-ddf1b6e1c28c.png)

**Comment by minhcasi** [comment]
@luisalf23 - please try to login to save the data
