### ISSUE TITLE
Duplicate Issue

### ISSUE THREAD

**Issue by ISma3eliano** [inspireui/fluxbuilder#169]
Hello, 

I can't activate my flux builder & my Mstore Api "wordpress integration" at the same time

**Comment by minhcasi** [comment]
it seems as a weird issue, we will investigate and fix it

**Comment by minhcasi** [comment]
Btw, I've removed the link to protect your purchase code - thank you

**Comment by ISma3eliano** [comment]
thanks, waiting for your fix

**Comment by minhcasi** [comment]
Fixed on latest release https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
