### ISSUE TITLE
Can't use it, always errors

### ISSUE THREAD

**Issue by ahmedsmag** [inspireui/fluxbuilder#170]
I have created the API, please check the screenshots
![Screenshot_20200804-051723__01](https://user-images.githubusercontent.com/39961244/89249543-ba34cf80-d612-11ea-83d4-ee83d841f8c3.jpg)
![Screenshot_20200804-051803__01](https://user-images.githubusercontent.com/39961244/89249544-bb65fc80-d612-11ea-8811-b029b06f3c0f.jpg)

**Comment by minhcasi** [comment]
@ahmedsmag - this bug is fixed on latest `1.0.7` - we will update in next couple of days - thank you!

**Comment by minhcasi** [comment]
Fixed on latest release https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
