### ISSUE TITLE
Creating Sup-Category FluxStore

### ISSUE THREAD

**Issue by MrStandby** [inspireui/fluxbuilder#171]
I want to do like this
main Category ->Sup Category->anther Sup category (not attribute)  is do able .

![fluxbuldercategory](https://user-images.githubusercontent.com/65818812/89281464-ce98bc80-d652-11ea-9fea-06c10d62058f.png)

**Comment by minhcasi** [comment]
@MrStandby - sorry this feature is not yet available, we have noted on our backlog and update it later - thank you!
