### ISSUE TITLE
Searching is not working in emulator 

### ISSUE THREAD

**Issue by chinchujosea** [inspireui/fluxbuilder#172]
+ Detail Issues: Searching is not working in emulator but it working on flux builder and added otion item name is not lising in cart page and only  parent item name is listing . but my requirement is to add option to cart list.

Log getting  while searching:

════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following StateError was thrown during a scheduler callback:
Bad state: No element

When the exception was thrown, this was the stack: 
#0      List.first (dart:core-patch/growable_array.dart:219:5)
#1      _FilterSearchAttributesState.afterFirstLayout (package:fstore/screens/search/widgets/filters/filter_search_attributes.dart:68:52)
#2      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
...

+ Product & version:
+ Flutter (or React Native) version: flutter
+ Testing Device/Simulator: google pixel 3xl

**Comment by minhcasi** [comment]
@chinchujosea - i'm sorry as we could only support for purchased customer, would you mind to update the verified code on this link http://verify.inspireui.com - We sincerely apologize for the delay and thank you for your time

**Comment by chinchujosea** [comment]
Please address the all issues.. I have facing three issues and you people are change the label to banner issues.

**Comment by chinchujosea** [comment]
@minhcasi  I am not able to add my purchase details in  text format. Could you please  address this concern??

**Comment by chinchujosea** [comment]
@minhcasi  searching is not working in emulator:

Here is the log:
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following StateError was thrown during a scheduler callback:
Bad state: No element
When the exception was thrown, this was the stack:
#0 List.first (dart:core-patch/growable_array.dart:219:5)
#1 _FilterSearchAttributesState.afterFirstLayout (package:fstore/screens/search/widgets/filters/filter_search_attributes.dart:68:52)
#2 AfterLayoutMixin.initState. (package:after_layout/after_layout.dart:10:38)
#3 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#4 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)

**Comment by chinchujosea** [comment]
@minhcasi  From last three days I didn't get any update from you guys..

**Comment by minhcasi** [comment]
Fixed on latest release https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7 and Fluxbuilder 1.7.7 - pls have a try and let us know
