### ISSUE TITLE
Several Image Issues On Fluxbuilder For Fluxstore WooCommerce - Flutter E-commerce Full App

### ISSUE THREAD

**Issue by thomasyi79** [inspireui/fluxbuilder#173]
Hi there! First of all, great application template! Really appreciate the time being saved due to this. Thank goodness I found it on Codecanyon. 
(Note: I am using FluxBuilder of InspireUI v1.0.6) So on to my questions:

1. The category tab on my fluxbuilder is not showing any images so how do I insert images onto these cards in the category page?
![categorypg](https://user-images.githubusercontent.com/54558693/89212708-f07e3a80-d591-11ea-9351-3b476aeba631.JPG)

2. My banner images on the homepage has been having some resolution issues. What is the correct image size needed for clear HD pictures to show? I've tried 600 x 300 pixels and even 1200 x 600 pixels but always got pixelated/fuzzy (see image below)
![bannerimage](https://user-images.githubusercontent.com/54558693/89212965-65517480-d592-11ea-91c9-3c8655a9af0d.JPG)

3. There's two parts to this issue. First part: some images that I upload to my wordpress backend do not show up on my Fluxbuilder upon pressing the "your site" option to upload an image. Second Part: When I click on upload image on fluxbuilder, the images just stay stuck on uploading. I've waited for over thirty minutes at one point just to see if it would work but in the end, it did not.

4. Is there an image size guide I can get in order to create and upload the correct image resolutions? I've had the logo image show up really small at one point too and am having diffficulty in finding the correct image sizes.

5. Is there a save button for this section in the fluxbuilder layout? It keeps reverting to default settings, thus forcing me to be unable to set my logo and the settings below.
![logoside](https://user-images.githubusercontent.com/54558693/89213786-9e3e1900-d593-11ea-8d84-ef99939516b6.JPG)

**Comment by minhcasi** [comment]
@thomasyi79 - we are working hard to release it on next week - v1.0.7 - thank you!

**Comment by minhcasi** [comment]
Please give a try with latest release https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7  and let us know your checking - thank you!
