### ISSUE TITLE
Fluxbuilder Connection with Magento Site problem (Rest Api is not connected)

### ISSUE THREAD

**Issue by ShahnazABH** [inspireui/fluxbuilder#174]
Our magento site is configured with the FluxstorePro-1.7.6. On connecting in Fluxbuilder, it is showing the error as shown in the attached screenshot. Looking forward for some support. Thank you!
<img width="708" alt="Screenshot (42)" src="https://user-images.githubusercontent.com/61077992/89420315-634cfa00-d6e7-11ea-82b3-9e09fa00f262.png">

**Comment by minhcasi** [comment]
@ShahnazABH - could you help to check if you have installed the `extension for magento` from the download package?

**Comment by ShahnazABH** [comment]
Thank you for responding. 
Yes, we have installed Mstore.zip from the Magento-extension directory in the downloaded package. 
Also, edited config.dart (in VS Code) by specifiying url and access token. Then on building the app on emulator, category names are being loaded. Rest all (category images, products,....) are either blank or gives error message.
We guess its an integration issue. Please help to figure out.

**Comment by minhcasi** [comment]
Please give a try with the release https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7 and let us know your checking - thank you!
