### ISSUE TITLE
Fluxbuilder : Getting a different type of a screen

### ISSUE THREAD

**Issue by ShahnazABH** [inspireui/fluxbuilder#175]
I cant understand why am I getting a different view of fluxbuilder as compared to those shown in the documentation.
Please have a look at the screenshots attached and suggest me to get the normal view,as this is really difficult for real time design.
![Screenshot (44)](https://user-images.githubusercontent.com/61077992/89496667-a2bf2900-d76f-11ea-94dd-05ea50185f72.png)

![Screenshot (45)](https://user-images.githubusercontent.com/61077992/89496682-a9e63700-d76f-11ea-9803-206f5a42fb43.png)

**Comment by minhcasi** [comment]
@ShahnazABH - it could cause by small resolution on your Window, please try to adjust the screen solution larger, we will also fix to improve this UX issue - thank you!

**Comment by ShahnazABH** [comment]
Thank you for the response. My current resolution is : 1920 x 1080, which is the largest. Can i know the recommended resolution for Fluxbuilder.

**Comment by minhcasi** [comment]
Fix on latest release - https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7- pls give a try and let us know
