### ISSUE TITLE
Can't Activate via MacOS version

### ISSUE THREAD

**Issue by cgdmohamed** [inspireui/fluxbuilder#176]
Hello, i can't activate the MacOS version and stuck on loading 
![2222](https://user-images.githubusercontent.com/16435049/89528009-9926d700-d7ea-11ea-852e-bc3abedbd79c.png)

**Comment by minhcasi** [comment]
@cgdmohamed - Thank you for the feedback.
Please help us to submit this form and fill all required info to continue with the support - http://verify.inspireui.com - please don't share the purchase code or screenshot public here as another user will use it for activation.

Also, try active it again as it could cause by the server issue

**Comment by minhcasi** [comment]
Fixed on latest release https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
