### ISSUE TITLE
Products are not displayed on the vendor page

### ISSUE THREAD

**Issue by artme-ishibashi** [inspireui/fluxbuilder#177]
Hello.
Great application, thank you very much.

I am using the WooCommerce WCFM plugin on Fluxstore Multi Vendor.

I can't see my product on the vendor page in Fluxbuilder.
The same was true for Android studio.

Builder10.6
WooCommerce 4.20
Mstore API 2.8.2

[https://www.loom.com/share/bc02478d2deb41abb66856a6f15d5cd9](url)

**Comment by minhcasi** [comment]
@artme-ishibashi - thank you for your feedback, would you mind to share the website URL and consumers + serect keys then send  to inspireui.team@gmail.com - also include your config json file - we will help to check and get back you shortly - thank you!

**Comment by artme-ishibashi** [comment]
Hello,

thank you for contacting.
I sent an email on August 11.
* Attached config file

Destination
inspireui.team@gmail.com

　　　Takashi　ishibashi
