### ISSUE TITLE
Error template MyListing 

### ISSUE THREAD

**Issue by danimmg** [inspireui/fluxbuilder#18]
Hello I use the mylisting template and is giving this error

![Capture08-04-2020-08 56 52](https://user-images.githubusercontent.com/59834619/78782360-480bf100-7978-11ea-8203-1ebc95cbbb96.jpg)
![Capture08-04-2020-09 01 32](https://user-images.githubusercontent.com/59834619/78782364-48a48780-7978-11ea-8ff6-16c23624574d.jpg)
![Capture08-04-2020-09 02 55](https://user-images.githubusercontent.com/59834619/78782367-493d1e00-7978-11ea-9676-7e1a2252b3a4.jpg)

**Comment by philipvu30** [comment]
Hi @danimmg 

Currently it does not support MyListing/ListingPro themes. They will be implemented in FluxBuilder 1.2.

Thank you for your interest.
