### ISSUE TITLE
2fa

### ISSUE THREAD

**Issue by usaitech** [inspireui/fluxbuilder#180]
do you have a 2fa document for this?

**Comment by usaitech** [comment]
also do you have sharing function to go with social media and our products we sell?

**Comment by minhcasi** [comment]
The 2FA is supported from your own social login platform (google, facebook..), it will not support from fluxbuilder. 

please help to clarify the second question via screenshot as we are not quite understand :)

**Comment by usaitech** [comment]
like how do our customers share our social media profile via the app or do they need to share from app store. eg if they like our stuff they can share if you understand what I mean

**Comment by minhcasi** [comment]
@usaitech - from the product detail Fluxstore app, you could use the Share Native function, it is not available from the Preview app from Fluxbuilder.

**Comment by usaitech** [comment]
is it for PRO only or for all of the apps
