### ISSUE TITLE
Don't work drag and drop option

### ISSUE THREAD

**Issue by kazimVahobov** [inspireui/fluxbuilder#181]
Don't work drag and drop option for change position of child elements in parent screen (Windows 10) - in android 9 worked
![image](https://user-images.githubusercontent.com/43565868/89758795-1790bb00-db02-11ea-8d90-741e646c244b.png)

**Comment by minhcasi** [comment]
Please try to use the latest release - https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
