### ISSUE TITLE
can`t upload images to fluxbuilder pro 1.6 

### ISSUE THREAD

**Issue by kahloot** [inspireui/fluxbuilder#182]
I have PURCHASED code
can`t upload images to fluxbuilder pro 1.6 
And please I need someone to install the app becose I don`t have an aydia for make app android and ios files

**Comment by minhcasi** [comment]
@kahloot - this issue fixed on latest release - https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7 - thank you!
