### ISSUE TITLE
can not active purchase code

### ISSUE THREAD

**Issue by MOOUDE** [inspireui/fluxbuilder#183]
Hello,
I can not active my purchase code in fluxbuilder v1.7 
it says I have to change the website URL and when code to change it, it says you have to activate 
so basically stay in that loop!

**Comment by swapnildesai5** [comment]
same cant activate when you click save it says click on build when you click on build it resets to demo link and activation won't happen

**Comment by minhcasi** [comment]
@MOOUDE @swapnildesai5 - could you help to share the screenshot issues - thank you!

**Comment by MOOUDE** [comment]
yes sure, basically when try to send to setup the data section I got this 
![Screen Shot 2020-08-14 at 2](https://user-images.githubusercontent.com/6555426/90245642-ba677300-de3b-11ea-9af0-a9e1433c0938.jpg)

and when try to activate my purchases it says you are using the default website url 

![Screen Shot 2020-08-14 at 2 35 05 PM](https://user-images.githubusercontent.com/6555426/90245711-dec34f80-de3b-11ea-8de3-dde313cc2aa1.png)

**Comment by minhcasi** [comment]
@vumanhsn97 - please help to check this issue

**Comment by swapnildesai5** [comment]
https://streamable.com/utnv03

**Comment by Youssef-Harby** [comment]
I have the same issue, Please Help

**Comment by Youssef-Harby** [comment]
I solved the problem by activating the license with android application (FluxBuilder android version) and login back in Windows and it works now.

**Comment by zarrarnyc** [comment]
I bought this software, and so far it has not been working for all the reasons listed above.
