### ISSUE TITLE
FluxBuilder is Always Down During Our Working Hours 

### ISSUE THREAD

**Issue by swapnildesai5** [inspireui/fluxbuilder#184]
FluxBuilder is always not working usually its back after an hour or so today is out for about 8 hours stuck in infinite loop of loading

![flux](https://user-images.githubusercontent.com/37268415/90137939-f983be80-dd7e-11ea-9409-33eb4614b5d6.JPG)

**Comment by minhcasi** [comment]
@swapnildesai5 - this issue is fixed on latest `1.0.7` - this issue cause by history bug on fluxbuilder - please help to update new version on today - thank you!

**Comment by swapnildesai5** [comment]
Updated to new version cant activate when you click save it says click on build when you click on build it resets to demo link and activation won't happen

**Comment by minhcasi** [comment]
@vumanhsn97 - could be related to #183
