### ISSUE TITLE
Flux Builder Not Activating And Not Loading My Second Purchased Item

### ISSUE THREAD

**Issue by swapnildesai5** [inspireui/fluxbuilder#187]
![flux 2](https://user-images.githubusercontent.com/37268415/90247807-10d6b080-de40-11ea-8a60-f8fa97f6f74e.JPG)

https://streamable.com/7g8zk9

**Comment by minhcasi** [comment]
@swapnildesai5 - could you help to share the login access to that we could debug this case - pls send privately to inspireui.team@gmail.com - thanks

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
