### ISSUE TITLE
is it for PRO only or for all of the apps

### ISSUE THREAD

**Issue by usaitech** [inspireui/fluxbuilder#188]
is it for PRO only or for all of the apps

_Originally posted by @usaitech in https://github.com/inspireui/fluxbuilder/issues/180#issuecomment-674037637_

**Comment by usaitech** [comment]
minhcasi commented 36 minutes ago
@usaitech - from the product detail Fluxstore app, you could use the Share Native function, it is not available from the Preview app from Fluxbuilder.

also for points is there only 1 type of plugin to use for woocommerce or we can use another integration

**Comment by minhcasi** [comment]
The native sharing is used for all the Fluxstore collections app - you could test it from the Product Detail on our app demo - thank you!

**Comment by usaitech** [comment]
also for points is there only 1 type of plugin to use for woocommerce or we can use another integration

**Comment by usaitech** [comment]
also how do you implement the sharing function?

**Comment by minhcasi** [comment]
The point feature is only compatible for the Woocommerce-points-and-rewards

You could test the sharing function from the Product Detial screen - thank you!

**Comment by minhcasi** [comment]
Let us know if you have any question - thank you!
