### ISSUE TITLE
Cant edit the build menu

### ISSUE THREAD

**Issue by MaxxBurn** [inspireui/fluxbuilder#189]
I am currently trying to build an android app using wordpress and the FluxBuilder app. The problem is that the build menu doesn't even allow me to add the purchase code. Yes I am logged in , and also im using the correct OS app(windows).

Also unsure if its meant to work this way but the dashboard menu only has 3 menus to go through. 

New app => Connection => Template but no option to let me create the app. 

Thanks.

**Comment by minhcasi** [comment]
@MaxxBurn - we confirm this is the UX bug, we will fix in 1-2 days - thank you!

**Comment by himanshushankhala** [comment]
Also facing the same issue since two days.

**Comment by masthan8** [comment]
Hi Guys,

I am too facing the same issue with the new updated fluxbuilder. Not able to go past the choose templates screen, nothing happens after selecting the template and also not able to add purchase code from the build menu.

**Comment by vumanhsn97** [comment]
@MaxxBurn @himanshushankhala @masthan8 
Please redownload fluxbuilder version v1.0.7: https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
Thanks!

**Comment by masthan8** [comment]
Working fine now..
