### ISSUE TITLE
website products are not syncing in the FluxBuilder

### ISSUE THREAD

**Issue by shah0203** [inspireui/fluxbuilder#19]
Hi,
 
I have configured & validate my website REST API keys in FluxBuilder and now when i am adding new products in my website it is not getting sync in FluxBuilder due to which i am not able to see new added products in FluxBuilder. Plz help me and share some helpful docs or videos.

**Comment by minhcasi** [comment]
@shah0203 - there is some limited from the Preview mobile from fluxbuilder that not updated the latest data when you update form the wordpress side, it will be load again when you back and refresh the setting

Please notice that one you release the app on Real app on Appstore, this issues will be resolved 

We will upload more product video on this link http://youtube.com/inspireui - thank you!
