### ISSUE TITLE
Can't add banner image + Icon is Missing

### ISSUE THREAD

**Issue by swapnildesai5** [inspireui/fluxbuilder#191]
Hello,

Guys we are in production mode and when you roll out updates and disable builders without even testing and support is after 3-4 days the flux builder:

- Flux Builder is not loading
- Add images in Banner button is missing 
- Flux Builder Can't Activate Products

Please Restore Old Version of FluxBuilder so we can work or just provide a Refund i've bought 2 softwares from you guys this is very unprofessional

**Comment by swapnildesai5** [comment]
![flux 3](https://user-images.githubusercontent.com/37268415/90309869-fa3e6100-def4-11ea-9c7e-6bbb1761daf4.JPG)

**Comment by minhcasi** [comment]
@swapnildesai5 - this is a bug on latest Fluxbuilder, we will apply new fixing in 1-2 days 

@vumanhsn97 - please follow up this issue - thank you!

**Comment by vumanhsn97** [comment]
@swapnildesai5 
Please redownload fluxbuilder version v1.0.7: https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
Thanks!

**Comment by swapnildesai5** [comment]
Tried 100 times redownload and install

**Comment by minhcasi** [comment]
@swapnildesai5 - this is the latest screenshot - you could see the plus button on bottom of the page - thanks 

<img width="1193" alt="Screen Shot 2020-08-19 at 09 20 27" src="https://user-images.githubusercontent.com/1459805/90584640-3a575980-e1fd-11ea-8a43-52c61ff55fe4.png">
