### ISSUE TITLE
can I edit Source code  of FluxStore Vendors.

### ISSUE THREAD

**Issue by MrStandby** [inspireui/fluxbuilder#193]
Hello ,any one know that if I buy FluxStore Vendors From (Inspireui Company) , Can i Edit on Flutter or dart language because There is Many things i want to change .
Thank you

**Comment by minhcasi** [comment]
@MrStandby - yes - you could edit the full source code from Fluxstore Multi vendor app with dart language. 

The Fluxbuilder is extra tools support for basic customization - thank you!
