### ISSUE TITLE
Problem Languages FluxStore Vendors  

### ISSUE THREAD

**Issue by MrStandby** [inspireui/fluxbuilder#195]
FluxStore Brings two languages(Arabic and English) on the item name , how can i let the FluxStore (FluxBuilder) get the Arabic name only or English only depend on chosen language .
thank you
![FluxStoreLangugeProblem](https://user-images.githubusercontent.com/65818812/90314763-f0315800-df1e-11ea-9d81-ce30d4ebcb61.png)

**Comment by minhcasi** [comment]
@MrStandby - this feature is not available - we will investigate to upgrade it on next release `1.0.8` - thank you!
