### ISSUE TITLE
Left Menu Not Saving

### ISSUE THREAD

**Issue by mbmendiola** [inspireui/fluxbuilder#198]
Good day.

I tried to change the logos and hide some options in the Left Menu, but it is not saving even if you click the save button. Once you leave the Left Menu settings, all the changes that you have made are all gone.

Looking forward to your feedback.

**Comment by vumanhsn97** [comment]
@mbmendiola 
Please redownload fluxbuilder version v1.0.7: https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.7
Thanks!
