### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by Gag1011** [inspireui/fluxbuilder#199]
Updating my bundle id has resulted in my app crashing every time i start it. I am using the fluxstore wcfm multi-vendor template. I followed the steps described here: https://docs.inspireui.com/fluxstore/delivery-android/ and it hasn't helped. Please assist asap!
I can't get the bash commands shown in the video to work either.

**Comment by minhcasi** [comment]
@Gag1011 - pls raise on the fluxstore support channel on this link - http://github.com/inspireui/support/issues - also attach your proof of purchasing - thank you for your time
