### ISSUE TITLE
URLs do not change

### ISSUE THREAD

**Issue by talalibdah** [inspireui/fluxbuilder#2]
I'm trying the Fluxbuilder, but everytime I change store URL and API keys, they do not save and get replaced with default ones all the time.

**Comment by hhhasnat** [comment]
I'm Also try it same problem in android version & Can't login in Window version. missing Plugin Exception

**Comment by minhcasi** [comment]
@talalibdah - @hhhasnat 
Please update the latest stable versions: 
+ Window OS: select the link https://github.com/inspireui/fluxbuilder/releases/download/1.0.0/FluxBuilder.1.0.zip
+ macOS: download from Appstore https://apps.apple.com/vn/app/fluxbuilder/id1500753204?mt=12
+ iPad/iPhone: download from Appstore https://apps.apple.com/tt/app/fluxbuilder-pro/id1503282735?ign-mpt=uo%3D2
+ tablet/android: download from Google Play https://play.google.com/store/apps/details?id=com.inspireui.fluxbuilderpro&hl=en
