### ISSUE TITLE
Flux builder vc_redist.x64  error

### ISSUE THREAD

**Issue by opooletech** [inspireui/fluxbuilder#20]
When am install this file : vc_redist.x64  this error is showing and flux builder desktop is not working 
please update me even am install android app flux builder and scan barcode still not working 

![image](https://user-images.githubusercontent.com/8824264/78900483-53ead680-7a90-11ea-93e1-d290e5b34500.png)

**Comment by minhcasi** [comment]
@opooletech - could you open the Fluxbuilder on window so far, please try to install the VC Dll from this link as well - thank you!

We will check the scan QR code on Android as well

**Comment by opooletech** [comment]
I will scann from android is not working

**Comment by minhcasi** [comment]
@opooletech could you share the screenshot issue please?

**Comment by minhcasi** [comment]
confirm this bug is fixed by copy dll to window/systems32 - let us know if you have any questions - thank you!
