### ISSUE TITLE
the code execution cannot proceed because msvcp140.dll was not found reinstalling the program may fix this problem

### ISSUE THREAD

**Issue by ahmedsmag** [inspireui/fluxbuilder#200]
the code execution cannot proceed because msvcp140.dll was not found reinstalling the program may fix this problem
I can't open the program on PC

**Comment by ahmedsmag** [comment]
Thank You, 
I have fixed the issue by downloading the file msvcp140.dll and place it on the C:\Windows\System32 folder.

**Comment by ahmedsmag** [comment]
The Program is now opened but it's so not responsive and can't log in, it not accepting my clicks on "Enter" on Keyboard, or ever through a click with the mouse on Login
Then show me a black screen!!

**Comment by ahmedsmag** [comment]
How to create my APK?
After done, where and how to create the apk file

**Comment by ahmedsmag** [comment]
1- How to use the code in Fluxstore to make APK and iOS files to upload on Google Play and Apple Store.
2- How to set the User Phone Verification and login with Phone Number?

**Comment by ahmedsmag** [comment]
The Program always revert my saved settings!!!, 
I thought after a long time with a new update it will work, but nothing improved!!

**Comment by minhcasi** [comment]
Hi ourfocnetwork - we have approved your request - thx

**Comment by ahmedsmag** [comment]
Because fstore depends on flutter_svg 0.8.0 which doesn't match any
versions, version solving failed.
pub get failed (1; Because fstore depends on flutter_svg 0.8.0 which
doesn't match any versions, version solving failed.)
