### ISSUE TITLE
Warning: You are using these overridden dependencies: ! flutter_svg 0.18.0

### ISSUE THREAD

**Issue by ahmedsmag** [inspireui/fluxbuilder#201]
I have run many command lines to install and upgrade the Dart SDK Version, but I still get the error below:

Running "flutter pub get" in source...                          

Warning: You are using these overridden dependencies:
! flutter_svg 0.18.0
Running "flutter pub get" in source...                              2.6s
Process finished with exit code 0

The current flutter version

****>flutter --version
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (5 days ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1

what should I do?

**Comment by minhcasi** [comment]
@ahmedsmag - this is not a bug, it overrides library method to fix the build - pls ignore if you could run the project normally - thanks

**Comment by ahmedsmag** [comment]
Because fstore depends on flutter_svg 0.8.0 which doesn't match any
versions, version solving failed.
pub get failed (1; Because fstore depends on flutter_svg 0.8.0 which
doesn't match any versions, version solving failed.)

**Comment by ahmedsmag** [comment]
I got this error

Because fstore depends on flutter_svg 0.8.0 which doesn't match any versions, version solving failed.
pub get failed (1; Because fstore depends on flutter_svg 0.8.0 which doesn't match any versions, version solving failed.)

**Comment by ahmedsmag** [comment]
I run a command --> flutter version 1.20.2 
It will help?

**Comment by ahmedsmag** [comment]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
lib/main.dart:30:1: Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
Try adding the name of the type of the variable or the keyword 'var'.
Warning: You are using these overridden dependencies:
^^^^^^^
lib/main.dart:30:1: Error: Expected ';' after this.
Warning: You are using these overridden dependencies:
^^^^^^^
lib/main.dart:30:8: Error: Expected a declaration, but got ':'.
Warning: You are using these overridden dependencies:
       ^
lib/main.dart:30:14: Error: Expected ';' after this.
Warning: You are using these overridden dependencies:
             ^^^
lib/main.dart:30:24: Error: Expected ';' after this.
Warning: You are using these overridden dependencies:
                       ^^^^^
lib/main.dart:30:41: Error: Expected ';' after this.
Warning: You are using these overridden dependencies:
                                        ^^^^^^^^^^^^
lib/main.dart:30:53: Error: Expected a declaration, but got ':'.
Warning: You are using these overridden dependencies:
                                                    ^
lib/main.dart:31:1: Error: Expected a declaration, but got '!'.
! flutter_svg 0.18.0
^
lib/main.dart:31:3: Error: Variables must be declared using the keywords 'const', 'final', 'var' or a type name.
Try adding the name of the type of the variable or the keyword 'var'.
! flutter_svg 0.18.0
  ^^^^^^^^^^^
lib/main.dart:31:3: Error: Expected ';' after this.
! flutter_svg 0.18.0
  ^^^^^^^^^^^
lib/main.dart:31:15: Error: Expected a declaration, but got '0.18'.
! flutter_svg 0.18.0
              ^^^^
lib/main.dart:31:19: Error: Expected a declaration, but got '.0'.
! flutter_svg 0.18.0
                  ^^
lib/main.dart:30:10: Error: Type 'You' not found.
Warning: You are using these overridden dependencies:
         ^^^
lib/main.dart:30:18: Error: Type 'using' not found.
Warning: You are using these overridden dependencies:
                 ^^^^^
lib/main.dart:30:30: Error: Type 'overridden' not found.
Warning: You are using these overridden dependencies:
                             ^^^^^^^^^^
lib/main.dart:30:10: Error: 'You' isn't a type.
Warning: You are using these overridden dependencies:
         ^^^
lib/main.dart:30:18: Error: 'using' isn't a type.
Warning: You are using these overridden dependencies:
                 ^^^^^
lib/main.dart:30:30: Error: 'overridden' isn't a type.
Warning: You are using these overridden dependencies:
                             ^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 1s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ahmedsmag** [comment]
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
> Failed to find Platform SDK with path: platforms;android-R

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 5s
Exception: Gradle task assembleDebug failed with exit code 1
