### ISSUE TITLE
Connectivity Issue - Unable to resolve "Regenerated Thumbnails is not working" issue even after following the required steps

### ISSUE THREAD

**Issue by marvinbenneth-appsintegra** [inspireui/fluxbuilder#202]
We have bought **Fluxstore WooCommerce - Flutter E-commerce Full App** and we wanted to use the FluxBuilder to design our mobile application. But when connecting our website in fluxbuilder, we are getting one error.

**"Regenerated Thumbnails is not working"**

We already did the required steps to resolve the issue suggested by the fluxbuilder app but the issue is still there.

Is there another way to resolve this issue. Thank you!

See attached screenshots for more info of the error.

![Connectivity Issue - Unable to resolve Regenerated Thumbnails is not working](https://user-images.githubusercontent.com/69909040/90646355-2e44b980-e248-11ea-915c-6e8d736967e4.png)

![Regenerated Thumbnails - Already did the following steps](https://user-images.githubusercontent.com/69909040/90646426-3f8dc600-e248-11ea-8fdd-7363be8dba11.png)

**Comment by Tecmesh** [comment]
Same Problem Here. Is Mandatory to pass all the checks to use FluxBuilder with my backed?

**Comment by aralom** [comment]
Same with me, all items pass just Thumbsnails give a error.

**Comment by vumanhsn97** [comment]
Please download this version: https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.8
Thanks!
