### ISSUE TITLE
Failed to find Platform SDK with path: platforms;android-R

### ISSUE THREAD

**Issue by ahmedsmag** [inspireui/fluxbuilder#203]
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

What went wrong:
Could not determine the dependencies of task ':app_settings:compileDebugAidl'.
Failed to find Platform SDK with path: platforms;android-R

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 4m 5s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by minhcasi** [comment]
sorry we have refunded your request and this ticket is no longer support - thanks

**Comment by ahmedsmag** [comment]
Hello,

I have purchased again, hope you can help me setup the application as soon
as possible
