### ISSUE TITLE
Backorder issue on Out of stock product.

### ISSUE THREAD

**Issue by itlakshmanan** [inspireui/fluxbuilder#205]
Some products was placed in backorder even we managed stock quantity and disabled backorder option.

This issue was randomly happening. We have more than 1400 products. Daily we are receiving 5 to 8 items on backorder. 

Kindly check this issue.

**Comment by minhcasi** [comment]
@itlakshmanan - this question is related to fluxstore product - pls give your question to https://github.com/inspireui/support/issues - thank you!
