### ISSUE TITLE
Products are not displayed on the vendor page

### ISSUE THREAD

**Issue by artme-ishibashi** [inspireui/fluxbuilder#206]
Hello.
Great application, thank you very much.

 sent the config file by email, but I posted it again because #177 was closed.
I look forward to hearing from you.

--------------------------------------------
I am using the WooCommerce WCFM plugin on Fluxstore Multi Vendor.

I can't see my product on the vendor page in Fluxbuilder.
The same was true for Android studio.

Builder10.6
WooCommerce 4.20
Mstore API 2.8.2

**Comment by artme-ishibashi** [comment]
I am waiting for a reply

**Comment by minhcasi** [comment]
@artme-ishibashi - could you help to download the latest release fluxbuilder 1.0.8?

**Comment by artme-ishibashi** [comment]
I have downloaded 1.0.8.
Same situation as 1.06.

I will contact you if you have any required information.
I look forward to reply.

**Comment by minhcasi** [comment]
@artme-ishibashi - could you help to share some screenshot issue pls

**Comment by artme-ishibashi** [comment]
share screenshot
[https://www.loom.com/share/567cae72cdbe4cfebde1e46fb5cceda3](url)
 1.0.8.
Link to vendor is unresponsive
The product is not displayed on the vendor page
