### ISSUE TITLE
not save left menu changes

### ISSUE THREAD

**Issue by malmont** [inspireui/fluxbuilder#207]
I use fluxbuilder for shopify
could not save left menu changes.

![Capture d’écran 2020-08-21 à 19 08 42](https://user-images.githubusercontent.com/70040545/90941979-c75b0800-e3e1-11ea-8d43-cbb57fb6da40.png)

**Comment by minhcasi** [comment]
@malmont - pls help to use latest release on this link https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.8
