### ISSUE TITLE
my categroies not show in fluxbuilder when i want ad categroies

### ISSUE THREAD

**Issue by emadpost2016** [inspireui/fluxbuilder#208]
There is an error when trying to add any products and sections on the main page, the sections of my site do not appear, knowing that the link was done correctly, but when the design is redesigned, the problem appears and the default application sections appear

**Comment by minhcasi** [comment]
@emadpost2016 - would you mind to share the screenshot issue pls?

**Comment by minhcasi** [comment]
also help us update to latest release to see if it can fix the issue - https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.8
