### ISSUE TITLE
The method '[]' was called on null.

### ISSUE THREAD

**Issue by smartbionix** [inspireui/fluxbuilder#209]
The following NoSuchMethodError was thrown building Consumer<AppModel>(dirty, dependencies: [_InheritedProviderScope<AppModel>]):
The method '[]' was called on null.
Receiver: null
Tried calling: []("Setting")

The relevant error-causing widget was: 
  Consumer<AppModel

**Comment by smartbionix** [comment]
Why haven't I heard from you guys?

**Comment by minhcasi** [comment]
@smartbionix - this question is related to fluxstore product, please help us to add a new ticket on https://github.com/inspireui/support/issues - thank you for your time!
