### ISSUE TITLE
Can i change the website wich is linked to my purchase code?

### ISSUE THREAD

**Issue by JSVDEV** [inspireui/fluxbuilder#21]
Hi,

for testing purposes i genreated a config file for a testing site. Now my purchase Code is connectet with this site - so i must maintain this Website forever to use FlexBuilder, because if I change the website, i get the error: "Your Code is already used by another Website"

**Comment by minhcasi** [comment]
@JSVDEV you can keep the Testing website if it has the same data with your product site - or you could request us to update the code with new product website, please send email to support@inspireui.com - thank you!
