### ISSUE TITLE
Fluxbuilder Not Working

### ISSUE THREAD

**Issue by dheerhold** [inspireui/fluxbuilder#210]
I have the app, but when I try to edit it it will not save&update to what I am changing it too.. My Shopify connection analysis passes the proper tests but it seems it is missing some products and some other info -- Any help is appreciated

Thanks
Danny

**Comment by minhcasi** [comment]
@dheerhold - could you confirm this issue happen on latest 1.0.8? https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.8

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!

**Comment by dheerhold** [comment]
Minh

I download the newer version and this is the error message I get below

(Picture attached)
