### ISSUE TITLE
FluxBuilder error: NoSuchMethodError, tried calling []("wcfm")

### ISSUE THREAD

**Issue by kaylabsco** [inspireui/fluxbuilder#213]
**For some reason, it keeps on showing:FluxBuilder error: NoSuchMethodError, tried calling []("wcfm")**

See image: [error: NoSuchMethodError  img](https://imgur.com/a/MSrNs7l)

+ Product & version: v1.0.8
+ Screenshot issues (drag the file to attach here): 

![Capture](https://user-images.githubusercontent.com/64433721/91210471-5471ca00-e71e-11ea-9b6b-ab25e55cb7ff.PNG)

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response or active conversation, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
