### ISSUE TITLE
Having issue running FluxBuilder on Windows 10

### ISSUE THREAD

**Issue by williamgurumayum** [inspireui/fluxbuilder#215]
Hello
I am having issue while running the program on Windows 10. Have copied the dll file as instructed to Windows/system32 folder and restarted PC but having this problem(attached). [https://prnt.sc/u9byj2](url)

Please help.

**Comment by Haniel5** [comment]
Please try this solution to solve the issue that msvcp140.dll does not exist https://www.sts-tutorial.com/download/msvcp140
