### ISSUE TITLE
Fluxbuilder not working

### ISSUE THREAD

**Issue by kyughost** [inspireui/fluxbuilder#216]
Hello, I bought the Multi-vendor and every time I try to use the macOS App. It unusable. I tried to create a new project and once I close the App everything will be gone. I will have a weird screen (check the attached file
<img width="1680" alt="Screen Shot 2020-09-02 at 15 09 33" src="https://user-images.githubusercontent.com/30949306/91987827-d5d4e800-ed2e-11ea-941f-0869bfc098f3.png">
)

**Comment by minhcasi** [comment]
@kyughost - could i know what is your MacOS version, please try to remove and reinstall the macos app from this link https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.8

**Comment by kyughost** [comment]
Hello I'm using macOS Catalina 10.15.6. I've downloaded it from that link and install it but still had the same issue

**Comment by kyughost** [comment]
> @kyughost - could i know what is your MacOS version, please try to remove and reinstall the macos app from this link https://github.com/inspireui/fluxbuilder/releases/tag/v1.0.8

Hello I'm using macOS Catalina 10.15.6. I've downloaded it from that link and install it but still had the same issue

**Comment by minhcasi** [comment]
pls try on Appstore - https://apps.apple.com/us/app/fluxbuilder/id1500753204?mt=12 - thank you!
