### ISSUE TITLE
unable to complete order in APP

### ISSUE THREAD

**Issue by shah0203** [inspireui/fluxbuilder#22]
Hi, when i am testing my App and trying to place one order it gives me below error message highlighted in RED color. plz help me to fix this issue by share any docs or related videos.

NOTE: my Product is FluxStore Woocommerce and backend is WooCommerce.

![image](https://user-images.githubusercontent.com/63024624/79022739-4f551980-7b87-11ea-9f4c-eb0c546cde33.png)

**Comment by minhcasi** [comment]
@vumanhsn97 - pls suggestion solution (i'm not sure if it is caused by the user login section from preview mode that conflict with the section from fluxbuilder)

**Comment by shah0203** [comment]
HI,

it got fixed as i was not using WC REST API Libraries. once i download the WC REST API libraries and incorporated my website REST API it started communicating with the APP and i can place the order successfully now. Thanks!
