### ISSUE TITLE
Purchase code being used by someone else

### ISSUE THREAD

**Issue by asagtc** [inspireui/fluxbuilder#221]
Hello,
I cannot build my app since it says someone else is using my purchase code.
I send you an email with everyhting and still my problem is not solved. I followed all of your instructions  and it still wont let me
Please help me I cannot wait any lone. Its now been more than 5 days since first interaction for this issue with you.

**Comment by minhcasi** [comment]
Pls send the request to reset purchase code to support@inspireui.com or you could raise to our new support ticket https://support.inspireui.com/
