### ISSUE TITLE
FluxBuilder 1.0.8 is not saving anything!

### ISSUE THREAD

**Issue by Beshoj** [inspireui/fluxbuilder#222]
Hi there,
Every time I change anything in the app and press "Save" it is not saving anything. And everything is getting reset automatically. HELP

**Comment by Beshoj** [comment]
I even tried 1.0.7 and nothing is good. I tried 1.0.6 and it is working fine. If I developed my app on fluxbuilder 1.0.6 will the performance of the app be bad or slow?

**Comment by minhcasi** [comment]
@Beshoj - there is no problem with the app version sir, please give a try with the latest 1.0.8

We are moving to new ticket support, please help to post your ticket to https://support.inspireui.com/
