### ISSUE TITLE
Page Connectivity failed

### ISSUE THREAD

**Issue by GeorgeMatcharashvili** [inspireui/fluxbuilder#223]
Hi, I'm getting this error message with the new FluxBuilder 1.0.8

![Аннотация 2020-09-13 120137](https://user-images.githubusercontent.com/71209074/93013361-edc32c00-f5b8-11ea-914b-3e5e383a468e.png)

**Comment by minhcasi** [comment]
@GeorgeMatcharashvili - there is no problem with the Pages if you could load the Data Review perfectly, we will remove this checking on next release - thank you!
