### ISSUE TITLE
Facing issue to run flux builder on windows 7 SP1

### ISSUE THREAD

**Issue by sonumas007** [inspireui/fluxbuilder#23]
The program can't start because VCRUNTIME140_1.dll is missing from your computer. Try reinstalling the program to fix the problem.

1) I have did it 2-3 time installing different different version of vc_redist.x64.exe but no use, any other solution so that i can also runn flux buillder for creating my app in that.

Thanks

**Comment by minhcasi** [comment]
@dttrung26 - please suggestion solution

**Comment by minhcasi** [comment]
@sonumas007 - could you try the solution on this ticket - https://github.com/inspireui/fluxbuilder/issues/4 - try to copy the DLL to Window/system32 and restart window
