### ISSUE TITLE
Access Code - Shopify

### ISSUE THREAD

**Issue by amankwatra** [inspireui/fluxbuilder#25]
Hi,

I installed the application and when i logged on and entered my shopify details it did not validate the settings.

I entered the access token which was made by us for GraphQL in the beginning and it did not work. Do i have to enter some other access token? How do i work with it?

Here is my proof of purchase. 
![image](https://user-images.githubusercontent.com/55830839/79078634-4b5ffd80-7d27-11ea-9db4-f6b6debde498.png)

**Comment by minhcasi** [comment]
@amankwatra - the fluxstore shopify is not yet compatible with Fluxbuilder, we are working on next upgrade to support for this product - thank you!
