### ISSUE TITLE
how to change currency ?

### ISSUE THREAD

**Issue by Rahuldh398** [inspireui/fluxbuilder#26]
My site is in Pound so how i can change as flux builer showing $?

also i have installed one plugin

https://wordpress.org/plugins/order-delivery-date-for-woocommerce/

now ->  There has been a critical error on your website. Please check your site admin email inbox for instructions.

Thank you

**Comment by Rahuldh398** [comment]
Another issue is that i am getting message that your code is being used by another website. how does that possible?

**Comment by minhcasi** [comment]
change current is not available from fluxbuilder, you could try to customize it as manually from the config folder of fluxstore

Please download the latest version that includes the Rest purchase code feature - thank you!
