### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by glpennino** [inspireui/fluxbuilder#28]
Hello,
i tried again but can't login. I also restarted the mac but it doesn't work. I tried to install also on a windows pc and it gives me the same problem.
I also uninstalled the app, cleared the cache and reinstalled. Nothing, the login remains hanging.
![Schermata 2020-04-17 alle 15 49 11](https://user-images.githubusercontent.com/44557088/79597241-3813b000-80e2-11ea-85b4-c8727e59aa16.png)

**Comment by minhcasi** [comment]
@glpennino - we will update the latest macOS version today - thank you!

**Comment by minhcasi** [comment]
fixed on mac os - pls download the latest macos version or download load it here - https://github.com/inspireui/fluxbuilder/releases
