### ISSUE TITLE
Login and Registration is not Working

### ISSUE THREAD

**Issue by Pankaj-Sakariya** [inspireui/fluxbuilder#3]
When I try to login with google or facebook, showing Platform method not found exception. 
Also not able to register as new user.

**Comment by jihadbek** [comment]
Yes , it is not working on windows 10

**Comment by Pankaj-Sakariya** [comment]
It is also not working in Windows 7

**Comment by minhcasi** [comment]
Please update the latest stable versions: 
+ Window OS: select the link https://github.com/inspireui/fluxbuilder/releases/download/1.0.0/FluxBuilder.1.0.zip
+ macOS: download from Appstore https://apps.apple.com/vn/app/fluxbuilder/id1500753204?mt=12
+ iPad/iPhone: download from Appstore https://apps.apple.com/tt/app/fluxbuilder-pro/id1503282735?ign-mpt=uo%3D2
+ tablet/android: download from Google Play https://play.google.com/store/apps/details?id=com.inspireui.fluxbuilderpro&hl=en
