### ISSUE TITLE
how to send geolocation data to woocommerce via order?

### ISSUE THREAD

**Issue by hytcelebi100068** [inspireui/fluxbuilder#30]
Hello, first of all thanks for the application. It works very well.

I just want to ask is there any way to send geo location to woocommerce backend? For now it just fills adress. I’m working with carriers and i want to make them job easier.

And about onboarding screen and banner slider photos. Is there no way to fix content show properly and complete? I tried all BoxFit options but none of them doesn’t meet my requests. I want to prepare templates for used in discount, product marketing etc. but it seems there is no standart for them.

And last about localization. I translated all strings placed on messages_en. But there is also strings placed on dart files to show exceptions, warnings, etc. I translated them too. It seems no error in my app but i’m afraid to this kind of tranlations going to cause an error. What should i do about this?

Thanks in advance.

**Comment by minhcasi** [comment]
@hytcelebi100068 - hi man we just reply your message - please raise the detail issue about fluxstore to https://github.com/inspireui/support/issues - very best!
