### ISSUE TITLE
API and Purchase Code Error

### ISSUE THREAD

**Issue by steinheil** [inspireui/fluxbuilder#32]
**API is Correct but is not working**
![2](https://user-images.githubusercontent.com/63489149/79680645-89d44b80-8244-11ea-9224-54fa1e253620.png)

**Activation is invalid**
![3](https://user-images.githubusercontent.com/63489149/79680649-8ccf3c00-8244-11ea-82bd-e794ac867a2d.png)

**Error of API Validation**
![1](https://user-images.githubusercontent.com/63489149/79680652-8f319600-8244-11ea-8e25-2a5b94c9aa6d.png)

**Comment by minhcasi** [comment]
@steinheil - we could not reproduce this issue, please send it privately to support@inspireui.com - thanks

**Comment by aishema2000** [comment]
This is happening to me too. After I input the website url and keys, I have above screenshot.
