### ISSUE TITLE
My purchase code is incorrect

### ISSUE THREAD

**Issue by aishema2000** [inspireui/fluxbuilder#33]
I am using fluxbuilder, but after inserting data, and finalizing design. I go to publish, I download my purchase code text file, I paste into fluxstore but it says code is not correct. What can I do?

Please help me. I purchased this app one month ago and up to now I am fighting to have it published but I got a lot of frustrations. 

Error screenshot:
![image](https://user-images.githubusercontent.com/15066381/79686623-16c9d580-8242-11ea-9abe-1482e94f6aae.png)

Proof of purchase:
![image](https://user-images.githubusercontent.com/15066381/79686653-4c6ebe80-8242-11ea-8eca-2a1c0d56decc.png)

**Comment by vumanhsn97** [comment]
@aishema2000 Please again. If it same error, Can you send your code to vumanhsn97@gmail.com

**Comment by aishema2000** [comment]
EMail sent... Thanks.

**Comment by aishema2000** [comment]
I managed to have the App working without fluxbuilder, because it was taking a lot of time, but now after launching app on my device I can not sign in. Here is the output in the debug console when I sign in with email or phone:

==================================
E/[EGL-ERROR](23198): __egl_platform_cancel_buffers:644: surface->num_buffers(4)
D/Surface (23198): Surface::disconnect(this=0x87e5e800,api=1)
D/GraphicBuffer(23198): unregister, handle(0x8abba6c0) (w:720 h:1344 s:720 f:0x1 u:f02)
D/View    (23198): [Warning] assignParent to null: this = DecorView@b80c15a[SignInHubActivity]
D/WindowClient(23198): Remove from mViews: DecorView@b80c15a[SignInHubActivity], this = android.view.WindowManagerGlobal@fa9f256
I/flutter (23198): type 'String' is not a subtype of type 'int' of 'index'
I/flutter (23198): token: eTG1JsOlPsI:APA91bFt25dgB845YX277pu_-NpnvzxMc1N4sCjndQr15S7m0R2jwvqKmdV9-IE0s3aqNECjqaljAg1hmYvm4WaFssHmWITJHdO0NoqGiPziyWeIJE7vgOFMWfGp8kO-uza36euR4ifU
W/DynamiteModule(23198): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(23198): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(23198): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
V/NativeCrypto(23198): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
I/ProviderInstaller(23198): Installed default security provider GmsCore_OpenSSL
I/System.out(23198): port:443

=============== 

I sent you details and my full source codes on your email vumanhsn97@gmail.com PLEASE ASSIST ME very urgently I have a deadline, I have been struggling for one month now. I am totally dead. Please save my me. Thanking you in advance.

**Comment by aishema2000** [comment]
Good day Support team... Did you receive my email? Did you receive my source codes? I am still waiting for your assistance, please let me know if there is any update. this is very urgent. Thanks

**Comment by aishema2000** [comment]
When revising your documentation I see this:
![image](https://user-images.githubusercontent.com/15066381/79859893-09435580-83d2-11ea-98e0-1681844646da.png)

How do I add it to the functions.php file? Where exactly? Is it a must?

I AM STILL WAITING FOR YOUR SUPPORT....

**Comment by aishema2000** [comment]
I have changed REST API keys, please see your email for new keys to use.

**Comment by aishema2000** [comment]
Additional info: When I connect using SMS, i get the code but after putting the code into the app, nothing happens, it continues loading, the debug console shows this:

![image](https://user-images.githubusercontent.com/15066381/79864973-abffd200-83da-11ea-866b-bebe17ac8055.png)

**Comment by minhcasi** [comment]
@aishema2000 - kindly post a new ticket to https://github.com/inspireui/support/issues for the product related to fluxstore  app - another team will help to support these issues mater 

Also, try to download the latest Fluxbuilder that support the Reset Purchase Code features :)
