### ISSUE TITLE
There is error in Fluxbuilder.1.1

### ISSUE THREAD

**Issue by haidarsalim** [inspireui/fluxbuilder#36]
There is an error in the program, some parts do not work

![33](https://user-images.githubusercontent.com/54249914/79761340-f7a67300-8329-11ea-81eb-8e8bdbf40556.JPG)

**Comment by haidarsalim** [comment]
The same error appears on all platforms even without using the website
I tried to use vpn it didn't work out the same error
You can watch the next video
https://i.top4top.io/m_15789z5ce0.mov
I'm from Iraq

**Comment by minhcasi** [comment]
HI @haidarsalim - pls download the latest 1.0.4 - it is fixed this issue - thank you!
