### ISSUE TITLE
Issue on Win 10 (no changes were made still the same issue on previous)

### ISSUE THREAD

**Issue by steinheil** [inspireui/fluxbuilder#37]
![1](https://user-images.githubusercontent.com/63489149/79812254-f6695a80-83aa-11ea-903d-835a0757bf23.png)
![2](https://user-images.githubusercontent.com/63489149/79812256-f79a8780-83aa-11ea-8470-f43c21b9db80.png)
![3](https://user-images.githubusercontent.com/63489149/79812257-f8331e00-83aa-11ea-97f9-8529f7eaaaea.png)
![image](https://user-images.githubusercontent.com/63489149/79812259-f9fce180-83aa-11ea-941a-a30b7fca5b11.png)

**Comment by dttrung26** [comment]
Hi @steinheil , 
please send me your site information via trung@inspireui.com. Have a nice day!
