### ISSUE TITLE
Reset activation

### ISSUE THREAD

**Issue by gugan7** [inspireui/fluxbuilder#38]
Hi Team,

I was testing Fluxbuilder with staging domain. Now i try to use my production domain and its saying that "Your code is being used by ..."

My Demo Domain: https://demo.nextcodelab.com/everfresh. 

Please help to reset it. Let me know if you need my License Code.

**Comment by minhcasi** [comment]
@gugan7 - could you try the latest version that supports the Reset Purchase Code feature - https://github.com/inspireui/fluxbuilder/releases/tag/latest
