### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Roupasafricanas** [inspireui/fluxbuilder#39]
Good evening. I bought the app a few days ago because I needed it for my store. I recruited someone to take care of the settings but they said that an error appears when adding products to the cart. I created a request here and was redirected to another one where the publication feed is blocked. I would like to have guidance on this. graciously

**Comment by minhcasi** [comment]
@Roupasafricanas - could you help to raise the issue on this GitHub - https://github.com/inspireui/support/issues
