### ISSUE TITLE
Flux Builder your code is not correct

### ISSUE THREAD

**Issue by nowsath** [inspireui/fluxbuilder#40]
Hello,

in Flux Builder Publish shows - Your code is not correct. Please help me to fix.

**Comment by minhcasi** [comment]
@gugan7 - could you try the latest version that supports the Reset Purchase Code feature - https://github.com/inspireui/fluxbuilder/releases/tag/latest

**Comment by gugan7** [comment]
Hi @minhcasi ,

Yes its working. Thank you for the help.
