### ISSUE TITLE
Fluxbuilder 1.0.3 couldn't add Product Layout

### ISSUE THREAD

**Issue by gugan7** [inspireui/fluxbuilder#41]
Hi Team,

Fluxbuilder 1.0.3 couldn't add Product Layout. Its giving error "Failed . Please delete it and create a new one. "

![image](https://user-images.githubusercontent.com/42231641/79867641-3cf1a000-8411-11ea-9b32-4262cd54f1db.png)

**Comment by minhcasi** [comment]
@gugan7 - could you help to share the website URL so that we could have a check - thank you!

**Comment by steinheil** [comment]
same issue on my mac

**Comment by gugan7** [comment]
@gugan7 , its https://mysegar.my. I tested on both Mac and Windows. Its the same error.

@steinheil . As a workaround , I copy paste the default product layout from mstore to json file and upload it to fluxbuilder. Once it appear it fluxbuilder , i modify it to my needs.

**Comment by upeksha** [comment]
Same Issue https://pothsl.com, please help

**Comment by minhcasi** [comment]
This issue is fixed on next release 1.0.4 - thank you!
