### ISSUE TITLE
transfer the license to a new domain

### ISSUE THREAD

**Issue by sadeq90** [inspireui/fluxbuilder#44]
Hi,

I want to transfer the license from http://sweetmamabh.com/ to dakakeenme.com because the previous domain was for testing only.

I couldn't find any option to disable or delete the license.

thank you,

**Comment by minhcasi** [comment]
@sadeq90 - could i check if you are using latest 1.0.3? Thank you!

**Comment by sadeq90** [comment]
Using 2.3.6

The MStore API Plugin which is used for the Mstore and FluxStore AppVersion 2.3.6 \| By InspireUI \| View details
--

**Comment by sadeq90** [comment]
@minhcasi

**Comment by minhcasi** [comment]
@sadeq90 - pls download the latest Fluxbuilder 1.0.4 - we have include the Reset Purchase code feature - thank you!
