### ISSUE TITLE
it doesn't retrive product image from the web.

### ISSUE THREAD

**Issue by thimiradulakshitha** [inspireui/fluxbuilder#45]
all products can see properly when connected with the website. but I can't see the product image. any idea about fix this?

**Comment by minhcasi** [comment]
@thimiradulakshitha - it could be missing require plugin from the wordpress site - https://wordpress.org/plugins/regenerate-thumbnails/

Could you share the website info so that we could help for checking, the latest release 1.0.4 will be fix this issue - thank you!

**Comment by thimiradulakshitha** [comment]
I fixed this. Thank you for your help.
Regards
Thimira Dulakshitha
