### ISSUE TITLE
How do i solve this problem ? (Listing categories not working)

### ISSUE THREAD

**Issue by incegozmuratcan** [inspireui/fluxbuilder#46]
How do i solve this problem ?
<img width="368" alt="Screen Shot 2020-04-25 at 02 16 40" src="https://user-images.githubusercontent.com/64310808/80278489-66574800-86ff-11ea-8aea-5b5860ad41a0.png">

**Comment by minhcasi** [comment]
@incegozmuratcan - could i know which the template that you are using for the FluxStore Listing ?

**Comment by incegozmuratcan** [comment]
Listeo

Minh Pham <notifications@github.com>, 26 Nis 2020 Paz, 14:11 tarihinde şunu
yazdı:

**Comment by incegozmuratcan** [comment]
I'm still waiting for an answer.

Murat Can İncegöz <incegozmuratcan@gmail.com>, 26 Nis 2020 Paz, 15:04
tarihinde şunu yazdı:

**Comment by minhcasi** [comment]
Hi @incegozmuratcan - pls download the latest 1.0.4 - it could be fixed this issue - thank you!

Or share us the detailed website so that we could help for checking
