### ISSUE TITLE
it's only 1.0.2 not 1.0.3 

### ISSUE THREAD

**Issue by sree1977** [inspireui/fluxbuilder#47]
hi what you are upload it's 1.0.2, please check and upload 1.03

**Comment by minhcasi** [comment]
@sree1977 - could i know if you are using Window or MacOS?

**Comment by sree1977** [comment]
windows

**Comment by minhcasi** [comment]
HI @sree1977  - pls download the latest 1.0.4 https://github.com/inspireui/fluxbuilder/releases - thank you!
