### ISSUE TITLE
Activation on Fluxbuilder, error "your code is being used by" my website

### ISSUE THREAD

**Issue by fede42D** [inspireui/fluxbuilder#50]
Hello, sorry to bother you, I just wanted to ask help for a problem with fluxbuilder.
I have purchased a license and connected my website with your program. 
The problem is that when I try to save it says that I have to activate the code first. The only way to insert it in the program is via publish section but when I press on activate code it says that is being used by the name of my site and does not do anything, It is seen as an error. How can I solve this problem? 
More info : It is the windows OS program connected to a woo commerce website 
Thank you

**Comment by minhcasi** [comment]
@fede42D - pls help send the request to reset email to support@inspireui.com - or your could use the latest Fluxbuilder to reset the purchase code - thank you!
