### ISSUE TITLE
XXX when Validation setting in Flux Builder

### ISSUE THREAD

**Issue by engbasselayman** [inspireui/fluxbuilder#52]
i add my ip & consume key & secret key 
but (status xxx
![Capture](https://user-images.githubusercontent.com/64425666/80390874-541b0c80-88ad-11ea-925c-750900624e9f.PNG)
)

**Comment by dasdev** [comment]
i have the same issue please help someone

**Comment by gerlandog** [comment]
I have the same issue, trying to set it up... I have recreated the keys 5 times, and could not set it up.
![Anotación 2020-04-28 115247](https://user-images.githubusercontent.com/21976353/80502281-c8ee5500-8946-11ea-9858-cfac421040ed.png)

**Comment by dasdev** [comment]
`I had to clear my site first than i activate both the builder and site after that it's working fine till now. but once it got error but for a while. so follow this step if you can : 
1. go to fluxbuilder login than activate it. 
2. go to site install mstore api 
3. put your key than submit.
hope will work.

**Comment by gerlandog** [comment]
Thanks for the answer.. i did follow your steps and now:
![Sin título](https://user-images.githubusercontent.com/21976353/80518923-8c7a2380-895d-11ea-8141-f3a3d803f563.png)

**Comment by vumanhsn97** [comment]
@gerlandog 
Please check your consume key and secret key. If it is not working, You can follow this solution: https://github.com/woocommerce/woocommerce/issues/19649

**Comment by gerlandog** [comment]
Thanks @vumanhsn97 , I tried this but also no luck.  :(

seems that we are in trouble!!

**Comment by gerlandog** [comment]
I downloaded v 1.0.4, but in the screen it show 1.0.3. and also when I try to validate api rest it stays for more tha one hour like this:
![Sin título](https://user-images.githubusercontent.com/21976353/80596334-9a32b600-89fc-11ea-8882-90d6c62655bb.png)
I am really looking forward to solve this issues in order to test it and buy it, but it seems offly difficult to make it run... Please, I would really be glado if someone could help me out.
www.amaranthusbakery.com
THANKS!!!

**Comment by minhcasi** [comment]
@engbasselayman - could you help to double-check this guide - https://docs.woocommerce.com/document/woocommerce-rest-api/

There is a step by step to check the rest Api - https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

**Comment by engbasselayman** [comment]
@minhcasi 
Thanks my problem solved in the last version.

**Comment by gerlandog** [comment]
@vumanhsn97 , could it be possible that rest api is not working becuase i have no licence?
![Sin título](https://user-images.githubusercontent.com/21976353/80611104-8ee98580-8a10-11ea-8403-c012b64680d0.png)
If so, I could only test this after buying... :(

**Comment by dasdev** [comment]
Yes first buy than will work fine.

**Comment by minhcasi** [comment]
@gerlandog - you could try to connect without install mstore-api, just enable the WooCommerce rest api and fill the require info :)

**Comment by minhcasi** [comment]
@Nazreenexe - you could share your purchase code to support@inspireui.com - thank you!
