### ISSUE TITLE
rest_forbidden status":403

### ISSUE THREAD

**Issue by kzbar** [inspireui/fluxbuilder#54]
hi 
what is the problem ?
https://elysiumsa.com/wp-json/wc/v2/flutter/category/cache?categoryIds=20&consumer_key=ck_******&consumer_secret=cs_47*********
{"code":"rest_forbidden","message":"\u0639\u0630\u0631\u064b\u0627\u060c \u063a\u064a\u0631 \u0645\u0633\u0645\u0648\u062d \u0644\u0643 \u0628\u0641\u0639\u0644 \u0647\u0630\u0627.","data":{"status":403}}

flutter: [elysiumApp][wocommerce_api][00:32:18.184915] getAsync END [endPoint:flutter/category/cache?categoryIds=17] url:flutter/category/cache?categoryIds=17
flutter: #0      WooCommerce.getCategoryCache (package:fstore/services/woo_commerce.dart:941:9)
<asynchronous suspension>
#1      WooCommerce.getCategoryWithCache (package:fstore/services/woo_commerce.dart:933:18)
#2      Services.getCategoryWithCache (package:fstore/services/index.dart:343:23)
#3      CategoryModel.getCategories (package:fstore/models/category/category_model.dart:30:26)
<asynchronous suspension>
#4      _AppInitState.loadInitData (package:fstore/app_init.dart:71:64)
<asynchronous suspension>
#5      _AppInitState.afterFirstLayout (package:fstore/app_init.dart:58:11)
#6      AfterLayoutMixin.initState.<anonymous closure> (package:after_layout/after_layout.dart:10:38)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1074:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1021:9)
#9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:822:7)
#10     <…>
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Exception: عذرًا، غير مسموح لك بفعل هذا.

**Comment by minhcasi** [comment]
@kzbar - pls help to raise this issue to http://github.com/inspireui/support/issues
