### ISSUE TITLE
The code is being used

### ISSUE THREAD

**Issue by engbasselayman** [inspireui/fluxbuilder#55]
Dears,
I use the code on a test server on cloud for only testing and i deleted it,
when i want to use flux builder on the actual server
this is the result
![123](https://user-images.githubusercontent.com/64425666/80607863-4b097700-8a36-11ea-81ef-3e7abf1512df.PNG)

Kindly support

**Comment by minhcasi** [comment]
@engbasselayman - pls help to send the purchase code to support@inspireui.com - we will help to reset it - thank you!
