### ISSUE TITLE
Logo image does not load from Fluxbuilder

### ISSUE THREAD

**Issue by samik9** [inspireui/fluxbuilder#56]
Hello, i got this issue, the logo image does not load, i tried multiple times and logo does not work 

![FluxBuilder of InspireUI 2020-05-03 21-29-05](https://user-images.githubusercontent.com/50071744/80932532-7c12e000-8d85-11ea-95aa-848730218e9b.jpg)

**Comment by minhcasi** [comment]
no worries, I could move it :D

**Comment by samik9** [comment]
Was my mistake, show logo was false
