### ISSUE TITLE
don't show anything ...

### ISSUE THREAD

**Issue by masoudv** [inspireui/fluxbuilder#57]
Hi
I installed successfully the app from AppStore and another step from your GitHub.
But after open the app, i see an empty window

@minhcasi @dttrung26 @vumanhsn97

**Comment by masoudv** [comment]
**My device :** 
MacBook Pro late 2011 with Mojave 10.14.4

**Comment by masoudv** [comment]
Hi,
I update my OS to 10.15, try again and problem fixed

**Comment by minhcasi** [comment]
@masoudv - could you help to share the screenshot issue so that we could reproduce the issue - thank you!
