### ISSUE TITLE
Error Fluxsbuilder Windows

### ISSUE THREAD

**Issue by phcaraujo** [inspireui/fluxbuilder#58]
Fluxbuilder not work in Windows.

![error](https://user-images.githubusercontent.com/20992411/81107790-1857f680-8eee-11ea-83ec-08f2677fc0ac.jpg)

**Comment by fabfeminacan** [comment]
facing the same issue

**Comment by sfeken15** [comment]
I have the same issue.

**Comment by phcaraujo** [comment]
I managed to solve by downloading the dll and placing it in the program folder.
