### ISSUE TITLE
Download code not formatted, and categories broken

### ISSUE THREAD

**Issue by abstractionltd** [inspireui/fluxbuilder#59]
Hey, I am having two issues:

1) the copied code pastes without formatting into Android Studio, which looks messy and is difficult to work with. It pastes as a single line

2) The code is adding a "tag=-1" to the category string when linking a banner to a category which means that none of the categories work.

**Comment by minhcasi** [comment]
@abstractionltd - could you help to share the screenshot issue, and the json content here so that we could help for checking - thank you!

**Comment by abstractionltd** [comment]
{"HorizonLayout":[{"layout":"logo","showLogo":true,"showMenu":true,"image":"https://i.imgur.com/S8EiiRL.png","showSearch":true},{"items":[{"category":17,"image":"https://littleoak.co.nz/wp-content/uploads/2020/04/hot_drinks.png","tag":-1,"padding":0}],"layout":"bannerImage","isSlider":false},{"items":[{"category":21,"image":"https://littleoak.co.nz/wp-content/uploads/2020/04/cold_drinks.png","tag":-1,"padding":0}],"layout":"bannerImage","isSlider":false},{"items":[{"padding":0,"category":27,"image":"https://littleoak.co.nz/wp-content/uploads/2020/04/sweet-treats.png","tag":-1}],"layout":"bannerImage","isSlider":false},{"items":[{"padding":0,"category":30,"image":"https://littleoak.co.nz/wp-content/uploads/2020/04/savoury-treats.png","tag":-1}],"layout":"bannerImage","isSlider":false},{"isSlider":false,"items":[{"tag":-1,"padding":0,"category":28,"image":"https://littleoak.co.nz/wp-content/uploads/2020/04/breads.png"}],"layout":"bannerImage"},{"items":[{"category":32,"image":"https://littleoak.co.nz/wp-content/uploads/2020/04/light-meals.png","tag":-1,"padding":0}],"layout":"bannerImage","isSlider":false},{"items":[{"tag":-1,"padding":0,"category":31,"image":"https://littleoak.co.nz/wp-content/uploads/2020/04/heat-and-eat.png"}],"layout":"bannerImage","isSlider":false},{"image":"","isSnapping":true,"name":"For the Pantry","layout":"threeColumn","category":29}],"Setting":{"MainColor":"#3FC1BE","ProductListLayout":"list","ProductDetail":"simpleType"},"TabBar":[{"layout":"profile","icon":"user","data":{"id":1,"container":{"height":0.5,"image":{"height":0.5,"width":1.0,"url":"https://images.unsplash.com/photo-1584352587534-5763683125b5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80","align":{"x":1.0,"y":1.0}},"header":{"align":{"x":-1.0,"y":0.8},"padding":{"horizontal":20.0,"vertical":10.0},"color":"#FFFFFF","background":"#000000","text":"About US"}},"subHeader":"This is sub heading","description":"This is description"},"pos":100},{"label":"Home","icon":"assets/icons/tabs/icon-home.png","layout":"home","pos":200},{"layout":"search","pos":300,"label":"Search","icon":"assets/icons/tabs/icon-search.png","size":24},{"pos":400,"label":"Category","url":"https://inspireui.com","categoryLayout":"subCategories","layout":"category","icon":"assets/icons/tabs/icon-category.png","title":""},{"layout":"wishlist","icon":"assets/icons/tabs/icon-heartthin.png","title":"","data":{"description":"This is description","id":1,"container":{"height":0.5,"header":{"color":"#FFFFFF","text":"About US","align":{"y":0.8,"x":-1},"background":"#000000","padding":{"horizontal":20,"vertical":10}},"image":{"height":0.5,"align":{"x":1,"y":1},"width":1,"url":"https://images.unsplash.com/photo-1584352587534-5763683125b5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2700&q=80"}},"subHeader":"This is sub heading"},"pos":500,"url":"https://inspireui.com"}]}

**Comment by abstractionltd** [comment]
That's the json content. When pasted into Android Studio it's just a single line of text and even some of the element layout is wrong:

![](https://screenshot.click/z2kmz-k5lm5.png)

Notice the **"tag":-1}** text in the json. this is causing the banner images linked to categories to not show anything

**Comment by minhcasi** [comment]
@abstractionltd - pls help to try latest Fluxbuilder 1.0.5 and Fluxstore 1.7.4 to fix this issue - thank you!
