### ISSUE TITLE
Not able activate license

### ISSUE THREAD

**Issue by ChristianVisvardis** [inspireui/fluxbuilder#6]
First of all I can't just copy and paste the code. When trying to input manually there is also problem.
For example my code start with da1a5937
whenever I am trying to put the code, after da1a593 it's becoming 7da1a593

**Comment by minhcasi** [comment]
Please update the latest stable versions: 
+ Window OS: select the link https://github.com/inspireui/fluxbuilder/releases/download/1.0.0/FluxBuilder.1.0.zip
+ macOS: download from Appstore https://apps.apple.com/vn/app/fluxbuilder/id1500753204?mt=12
+ iPad/iPhone: download from Appstore https://apps.apple.com/tt/app/fluxbuilder-pro/id1503282735?ign-mpt=uo%3D2
+ tablet/android: download from Google Play https://play.google.com/store/apps/details?id=com.inspireui.fluxbuilderpro&hl=en
