### ISSUE TITLE
Fluxbuilder v.1.0.4 - login / signup fails

### ISSUE THREAD

**Issue by Ecoent** [inspireui/fluxbuilder#61]
the new fluxbuilder windows version 1.0.4 (Desktop app), fails to signup or login.
it does not allow new user id creation either.

![fbuilder signup fails](https://user-images.githubusercontent.com/44745681/81306217-38ea9280-904d-11ea-8c3a-fe2df55471c3.JPG)

**Comment by minhcasi** [comment]
@Ecoent - could i confirm if you are using latest 1.0.4 version?

**Comment by Ecoent** [comment]
Hi Minh,

Thats correct, downloaded on May 7th.
Also, there are no instructions of login id creation or anything new
process to create or use any id / password.

Thanks
Jim

**Comment by shah0203** [comment]
HI,
Even i am facing the same issue, i am unable to login to fluxbuilder with my ID. when i enter my credentials it just keep on loading without any further proceedings.

**Comment by minhcasi** [comment]
@shah0203 - pls try to download the latest version 1.0.5 - thank you!
