### ISSUE TITLE
Flux Builder not importing listings or categories

### ISSUE THREAD

**Issue by sfeken15** [inspireui/fluxbuilder#62]
Hi, Im not able to get Flux builder import any of the listings on my website.  It imports Blogs and blog categories fine however none of the listings.

Also, is there a way to activate the webview option?

**Comment by minhcasi** [comment]
Could you share the detail json import, and screenshot issue so that we could help to check the issues

The Webview is only working on ios or android of Fluxbuilder, you could also use the iPad for testing.
