### ISSUE TITLE
FluxNews 

### ISSUE THREAD

**Issue by vnatius** [inspireui/fluxbuilder#63]
was able to use the flux builder and its really easy to customise but when I try to analyse the system still shows “The image cache is not enabled” and I have installed the regenerate thumbnail plugins and I have followed the steps but it still gives this error when I analyse the system from the flux builder And how can I get the logo found on the user login page of FLUXNEWS?

**Comment by vnatius** [comment]
hello you are not saying anything

**Comment by vnatius** [comment]
Hello I got your template but I have lots of issues with it... I noticed that not all the categories are showing and I noticed the walkthrough images aren't fitting when I try to change it even when I use the exact image dimensions. I am working on my blog but I am sincerely not comfortable with these observations and I was able to use the flux builder and its really easy to customise but when I try to analyse the system still shows “The image cache is not enabled” and I have installed the regenerate thumbnail plugins and I have followed the steps but it still gives this error when I analyse the system from the flux builder And I can't build the flux APK, it gives errors when I try to build. Still 
<img width="377" alt="Screenshot 2020-05-09 at 10 09 57" src="https://user-images.githubusercontent.com/24778487/81469634-f906e500-91dd-11ea-8522-a58883681b3d.png">
<img width="377" alt="Screenshot 2020-05-09 at 10 10 03" src="https://user-images.githubusercontent.com/24778487/81469639-fd330280-91dd-11ea-8d42-eb3578c237b3.png">
![Screenshot_1589016674](https://user-images.githubusercontent.com/24778487/81470052-7d5a6780-91e0-11ea-8b47-c7051c185e88.png)
![Uploading Screenshot_1589016683.png…]()



no response yet on my previous ticket.

**Comment by minhcasi** [comment]
@vnatius - thank you for your feedback, it's about the new feature upgrade so that we have noted as a feature request and need more time to upgrade it

It's possible to process refund if you are not happy with the product

**Comment by vnatius** [comment]
Please I need a refund. I am not happy with this

**Comment by vnatius** [comment]
still no response.. since you can't help in fixing this, then you can process the refunds. I am not comfortable with the issues being faced. I can't build the APK file for this, the categories are not coming up some of them and the customisation of most of the screens are not working.. I dropped my screenshots here... you can process the refund and I will look for another option ... Thank you

**Comment by minhcasi** [comment]
@vnatius - you could submit on this link https://help.market.envato.com/hc/en-us/articles/202821460-Can-I-Get-A-Refund- - thanks
