### ISSUE TITLE
1.0.4 Not installed

### ISSUE THREAD

**Issue by grnas00** [inspireui/fluxbuilder#64]
Dear,,
Thanks for this amazing program ,
i have an problem when try install new version 1.0.4 after install and open i found the version is 1.0.3
and in home page when design new page get error "BOTTOM OVERFLOWED BY 2.0 PIXELS"
Please your advice to solve it
![Error](https://user-images.githubusercontent.com/24503019/81358876-646a8d00-90e0-11ea-97ed-e5079cefa874.png)

**Comment by grnas00** [comment]
What answer am I waiting for to publish my app
But this problem delayed me a lot time

**Comment by minhcasi** [comment]
@grnas00 - pls help to download the latest Fluxbuilder 1.0.5 and Fluxstore 1.7.4 to fix this issue - thank you!
