### ISSUE TITLE
[Fluxbuilder] .Rar file is corrupted.

### ISSUE THREAD

**Issue by tjain90** [inspireui/fluxbuilder#66]
Unable to extract or use fluxbuilder latest version. It throws corrupted rar file error.

**Comment by shah0203** [comment]
Even i am facing same issue. please help.

**Comment by minhcasi** [comment]
@tjain90 - pls use this file https://github.com/inspireui/fluxbuilder/releases/download/1.0.4/FluxBuilder_macOS.zip

**Comment by tjain90** [comment]
@minhcasi  Thnaks for this. Can you please provide this for windows
