### ISSUE TITLE
fluxbuilder_windows.rar is 

### ISSUE THREAD

**Issue by shah0203** [inspireui/fluxbuilder#68]
Hi,

when i downloaded "fluxbuilder_windows.rar" 1.0.4 and extracted it gives me below error message.

**"The archive is either in unknown format or damaged"**

**Comment by minhcasi** [comment]
@shah0203 - pls use this file https://github.com/inspireui/fluxbuilder/releases/download/1.0.4/FluxBuilder_macOS.zip - it works fine

**Comment by shah0203** [comment]
But i need Windows version. The one you provided seems to be Mac Os version.
