### ISSUE TITLE
Facing issues in Flux Builder

### ISSUE THREAD

**Issue by Amitjeypore** [inspireui/fluxbuilder#69]
I have installed all the provided plugins:
But I am getting the following errors:

Status: Image Cache Is Not Enabled
Banner Slider: When set for Categories when clicked I get no products page, Category product show well for category link but doesnt work with banner.

**Comment by Amitjeypore** [comment]
Ok additional issue, the product page the products show fine but when i change the layout to 3x3 the page says no products found.

**Comment by minhcasi** [comment]
@Amitjeypore - could i check if you have run the Regenerate the image from WP site - https://docs.inspireui.com/fluxnews/getting-started/#setup-the-regenerate-thumbnails-plugin 

Please also share the detailed screenshot and your website URL so that we could have a check :)

**Comment by Amitjeypore** [comment]
Yes will provide the above,

Have come up with additional issues:

Need to change privacy policy text in signup screen, the one I could point out in flutter inspector is auto generated one I10n.dart, nut this one doesnt change anything even if modified, please let me know what has to be modified.

Header image in Profile/Settings page of that lemon. Need to change that. How can I change it,

![Screenshot_20200512-175354](https://user-images.githubusercontent.com/65069372/81690955-b19c8500-9479-11ea-8bb3-80bfe39d2070.jpg)
![Screenshot_20200512-172215](https://user-images.githubusercontent.com/65069372/81690959-b2351b80-9479-11ea-9e93-310a60820923.jpg)
![Screenshot_20200512-172220](https://user-images.githubusercontent.com/65069372/81690962-b2cdb200-9479-11ea-8da1-991ca9f5bf3d.jpg)
