### ISSUE TITLE
Issue with Moving Codes from FlexBuilder to Android Studio

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/fluxbuilder#71]
Hello, 

When I complete the fulxbuilder setup and try to copy the codes to AndroidStudio, All codes get pasted in one single line.

![qIbpuz1 - Imgur](https://user-images.githubusercontent.com/58846483/81505895-53a05e00-9310-11ea-942e-7d5ba12c1800.jpg)

And when I run it I am getting below error

![gqdUE3V - Imgur](https://user-images.githubusercontent.com/58846483/81505904-60bd4d00-9310-11ea-9cb9-68aa47ff40b6.jpg)

**Comment by grnas00** [comment]
Unfortunately the same problem

**Comment by ishaq-ishaq** [comment]
I've the same problem here

**Comment by vumanhsn97** [comment]
Fluxbuilder v1.0.4 just support for Fluxstore v1.7.0. In lasted version in Fluxstore, you need to add StickyHeade: true/false in Settings https://tppr.me/WOvZ

**Comment by HarrySmith01** [comment]
> 
> 
> Fluxbuilder v1.0.4 just support for Fluxstore v1.7.0. In lasted version in Fluxstore, you need to add StickyHeade: true/false in Settings https://tppr.me/WOvZ

I have used second template and it does not have such code in setting.

**Comment by minhcasi** [comment]
@HarrySmith01 - please help to download latest Fluxbuilder 1.0.5 and Fluxstore 1.7.4 to fix this issue 👍
