### ISSUE TITLE
Changes are not getting saved.

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/fluxbuilder#72]
Hello,

I have customized fluxstore vendor and designed our app but everything we start the fluxBuilder we need to start everything from new.

If we make a lot of changes and open the fluxstore builder again then it ask us to start everything from new.

I am not sure if it is a bug or Fluxstore does not have feature to save our data.

**Comment by minhcasi** [comment]
Hi, the final output from the Fluxbuilder is expo as the config json file - if you have change/customize the Fluxstore source code, it will not impact to the app.

If you have apply the json config from the mstore-api then you could able to load your previous config by using this feature - https://tppr.me/59DuW

Let us know if you have any question :)

**Comment by HarrySmith01** [comment]
Apply website data is not available in my case.

I have downloaded the latest version of fluxbuilder bit still it says version 1.0.3

So maybe due to old version I Do not see that option.

However json copy looks working.

however, can you make changes so I do not need to enter web address. API information and license key again and again when I restart the app each time?

**Comment by minhcasi** [comment]
@HarrySmith01 - please download the latest stable version 1.0.5 👍 

The web address will be saved into the product history after you active the license - thank you!
