### ISSUE TITLE
Issue with banner image upload FluxStore MultiVendor

### ISSUE THREAD

**Issue by HarrySmith01** [inspireui/fluxbuilder#73]
Hello,

FluxBuilder does not provide option to upload Image.

When I click on Upload option, I get below screen.

![Capture](https://user-images.githubusercontent.com/58846483/81533389-bbdc5780-9383-11ea-94aa-7e7d5f7e8aab.JPG)

And When I click on "File Folder" I get back to the same page where I get upload option and if I click on it then again it will ask for File Folder or Link etc but actually, it does not provide option to upload an image.
![Capture1](https://user-images.githubusercontent.com/58846483/81532922-e4178680-9382-11ea-914e-ff1b161bc6ca.JPG)

**Comment by dttrung26** [comment]
Hi @HarrySmith01 , 
please download again FluxBuilder for Windows and kindly confirm if it works. I've just put an update for this issue. 
Many thanks.

**Comment by HarrySmith01** [comment]
Hi, 

Just checked with new downloaded one and And it is fixed.
