### ISSUE TITLE
Activation problem

### ISSUE THREAD

**Issue by engbasselayman** [inspireui/fluxbuilder#75]
when i want to activate the builder
 with my code it gives me an error.
Note: i used the code for the ip in the photo but for test.
![1](https://user-images.githubusercontent.com/64425666/81605159-57e08000-93d1-11ea-8896-b028ed3be11c.PNG)

**Comment by engbasselayman** [comment]
kindly any one can support me.
I published the problem from a week.

**Comment by vumanhsn97** [comment]
@engbasselayman 
Can you send your purchase code to vumanhsn97@gmail.com? I will reset it

**Comment by engbasselayman** [comment]
Done

**Comment by engbasselayman** [comment]
i sent it
