### ISSUE TITLE
Rest API Not Working and many issues

### ISSUE THREAD

**Issue by Amitjeypore** [inspireui/fluxbuilder#77]
Suddenly WP Rest API Stopped working, all the plugins are installed properly and keys are active but fluxbuilder says Rest API is not connected, then my products and categories started disappearing.
And now I get a red error screen as attached below, let me know what all you guys need to get the error fixed, My app was almost done. Now I dont at all have the patience to rebuild from scratch, please help.

website url: www.unostop.in
![Screenshot_1589308752](https://user-images.githubusercontent.com/65069372/81732725-84b69500-94ae-11ea-9ec1-8cf449dd305b.png)
![Capture1](https://user-images.githubusercontent.com/65069372/81732727-8718ef00-94ae-11ea-9380-f51ead94e1e2.PNG)

Step 2 (require): verify license and sharing config files via this google form - Already uploaded

Previous approved ID: inspireui/support#3127

*Important Note:* 
- Please help to fill the required information from the above 2 steps and don't share the public screenshot purchase here, we may close the ticket which is not included the proof of purchase. Kindly help us to create only 1-Ticket & includes all the issues, that would help us focus to resolve it better. 
- If your all ticket was resolved & closed, but would like to create a new ticket, then you don't need to submit the form again, just do simple step by linking to the previous verified ID, example: #Ticket-ID
Thank you so much for your time 😊

**Comment by Amitjeypore** [comment]
Yes you can remove it in the flux builder itself, you have an option called hide menu. Please check.

**Comment by Amitjeypore** [comment]
Any update on this issue ?

**Comment by harjono-flux** [comment]
Ohh ya i got it, thx. If want to change the that menu icon, can you?

Not yet, im still waiting. This is big issue, many people have problem in fluxstore 1.7.3
https://github.com/inspireui/support/issues/3151

**Comment by Amitjeypore** [comment]
No not have been able to do that.

**Comment by Amitjeypore** [comment]
My fluxbuilder says the rest api is not connected
and when i click the info button it says error "Handshake error in client"

**Comment by Amitjeypore** [comment]
Please help I am stuck

**Comment by Amitjeypore** [comment]
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18362.778], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!

**Comment by Amitjeypore** [comment]
main.dart

Launching lib\main.dart on ONEPLUS A6010 in debug mode...
Running Gradle task 'assembleDebug'...
Parameter format not correct -
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\connectivity-0.4.8+5\android\src\main\java\io\flutter\plugins\connectivity\ConnectivityBroadcastReceiver.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.5\android\src\main\java\io\flutter\plugins\urllauncher\WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\webview_flutter-0.3.21\android\src\main\java\io\flutter\plugins\webviewflutter\FlutterWebView.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: C:\Flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.9+2\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/Pizza.png.
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/Health.png.
I/flutter (21785): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/Grocery.png.
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/Health.png.
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/Pizza.png.
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/Health.png.
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/Grocery.png.
I/flutter (21785): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (21785): Receiver: null
I/flutter (21785): Tried calling: statusCode
I/flutter (21785): fetchProductsByCategory: products?status=publish&lang=en&per_page=20&page=1&category=92
I/flutter (21785): url https://unostop.in/wp-json/wc/v2/products?status=publish&lang=en&per_page=20&page=1&category=92
I/flutter (21785): [2020-05-13 16:47:16.942018Z][Fluxstore][wocommerce_api][22:17:16.941949] getAsync START [endPoint:products?status=publish&lang=en&per_page=20&page=1&category=92] url:https://unostop.in/wp-json/wc/v2/products?status=publish&lang=en&per_page=20&page=1&category=92&consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (21785): screenName null
E/flutter (21785): [ERROR:flutter/third_party/txt/src/minikin/FontFamily.cpp(184)] Could not get cmap table size!
E/flutter (21785): 
F/flutter (21785): [FATAL:flutter/third_party/txt/src/minikin/FontCollection.cpp(95)] nTypefaces == 0
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Debug service listening on ws://127.0.0.1:52096/F3YBoQhBeQs=/ws
Syncing files to device ONEPLUS A6010...
I/flutter (23721): [2020-05-13 16:47:37.215224Z][Fluxstore][main] ============== main.dart START ==============
D/PhoneWindow(23721): setNavigationBarColor: ff000000
I/flutter (23721): [2020-05-13 16:47:37.310884Z][Fluxstore][AppState] initState
I/flutter (23721): [2020-05-13 16:47:37.320330Z][Fluxstore][AppState] build
I/flutter (23721): [2020-05-13 16:47:37.345135Z][Fluxstore][AppState] build Theme
I/flutter (23721): screenName /
I/flutter (23721): [2020-05-13 16:47:38.192809Z][Fluxstore][AppState] Inital Data
I/flutter (23721): [2020-05-13 16:47:38.234646Z][Fluxstore][Services] setAppConfig: --> woo <--
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/flutter/cache
I/flutter (23721): [2020-05-13 16:47:38.287125Z][Fluxstore][wocommerce_api][22:17:38.286488] getAsync START [endPoint:flutter/cache] url:https://unostop.in/wp-json/wc/v2/flutter/cache?consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): [2020-05-13 16:47:38.343951Z][Fluxstore][AppState] init mobile modules ..
I/flutter (23721): [2020-05-13 16:47:38.354045Z][Fluxstore][AppState] register modules .. DONE
I/flutter (23721): [2020-05-13 16:47:38.481897Z][Fluxstore][MyConnectivity] online
I/flutter (23721): [2020-05-13 16:47:38.495708Z][Fluxstore][App] internet issue change: {ConnectivityResult.wifi: true}
I/flutter (23721): [2020-05-13 16:47:38.503684Z][Fluxstore][MyConnectivity] online
I/flutter (23721): [2020-05-13 16:47:38.504048Z][Fluxstore][App] internet issue change: {ConnectivityResult.wifi: true}
I/flutter (23721): [Debug] Finish Load AppConfig
I/flutter (23721): [2020-05-13 16:47:38.859768Z][Fluxstore][AppState] Init Data Finish
I/flutter (23721): [2020-05-13 16:47:38.866185Z][Fluxstore][Category] getCategories
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/products/categories?exclude=311&per_page=100&page=1&lang=en
I/flutter (23721): [2020-05-13 16:47:38.869197Z][Fluxstore][wocommerce_api][22:17:38.869120] getAsync START [endPoint:products/categories?exclude=311&per_page=100&page=1&lang=en] url:https://unostop.in/wp-json/wc/v2/products/categories?exclude=311&per_page=100&page=1&lang=en&consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/products/tags
I/flutter (23721): [2020-05-13 16:47:38.874877Z][Fluxstore][wocommerce_api][22:17:38.874805] getAsync START [endPoint:products/tags] url:https://unostop.in/wp-json/wc/v2/products/tags?consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/products/attributes
I/flutter (23721): [2020-05-13 16:47:38.877125Z][Fluxstore][wocommerce_api][22:17:38.877045] getAsync START [endPoint:products/attributes] url:https://unostop.in/wp-json/wc/v2/products/attributes?consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): [2020-05-13 16:47:38.880041Z][Fluxstore][AppState] build Theme
E/flutter (23721): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (23721): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
E/flutter (23721): 
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/flutter/category/cache?categoryIds=
I/flutter (23721): [2020-05-13 16:47:39.403863Z][Fluxstore][wocommerce_api][22:17:39.403745] getAsync START [endPoint:flutter/category/cache?categoryIds=] url:https://unostop.in/wp-json/wc/v2/flutter/category/cache?categoryIds=&consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): getFilterAttributes: HandshakeException: Handshake error in client (OS Error: 
I/flutter (23721): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
I/flutter (23721): getFilterTags: HandshakeException: Handshake error in client (OS Error: 
I/flutter (23721): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
I/flutter (23721): 
E/flutter (23721): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (23721): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
E/flutter (23721): 
I/flutter (23721): screenName null
I/flutter (23721): [2020-05-13 16:47:40.531598Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
I/flutter (23721): [2020-05-13 16:47:40.595104Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
I/flutter (23721): [2020-05-13 16:47:40.799640Z][Fluxstore][Home] initState
I/flutter (23721): [2020-05-13 16:47:40.806971Z][Fluxstore][Home] build
I/flutter (23721): [2020-05-13 16:47:41.368013Z][Fluxstore][Category] getCategories
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/products/categories?exclude=311&per_page=100&page=1&lang=en
I/flutter (23721): [2020-05-13 16:47:41.368841Z][Fluxstore][wocommerce_api][22:17:41.368777] getAsync START [endPoint:products/categories?exclude=311&per_page=100&page=1&lang=en] url:https://unostop.in/wp-json/wc/v2/products/categories?exclude=311&per_page=100&page=1&lang=en&consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/products/attributes
I/flutter (23721): [2020-05-13 16:47:41.369847Z][Fluxstore][wocommerce_api][22:17:41.369807] getAsync START [endPoint:products/attributes] url:https://unostop.in/wp-json/wc/v2/products/attributes?consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/products/tags
I/flutter (23721): [2020-05-13 16:47:41.370293Z][Fluxstore][wocommerce_api][22:17:41.370261] getAsync START [endPoint:products/tags] url:https://unostop.in/wp-json/wc/v2/products/tags?consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/products?lang=en&status=publish&category=92
I/flutter (23721): [2020-05-13 16:47:41.374985Z][Fluxstore][wocommerce_api][22:17:41.374933] getAsync START [endPoint:products?lang=en&status=publish&category=92] url:https://unostop.in/wp-json/wc/v2/products?lang=en&status=publish&category=92&consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/products?lang=en&status=publish&category=255&per_page=20
I/flutter (23721): [2020-05-13 16:47:41.375820Z][Fluxstore][wocommerce_api][22:17:41.375788] getAsync START [endPoint:products?lang=en&status=publish&category=255&per_page=20] url:https://unostop.in/wp-json/wc/v2/products?lang=en&status=publish&category=255&per_page=20&consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
E/flutter (23721): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (23721): At this point the state of the widget's element tree is no longer stable.
E/flutter (23721): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (23721): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3781:9)
E/flutter (23721): #1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3795:6)
E/flutter (23721): #2      Element.findAncestorStateOfType (package:flutter/src/widgets/framework.dart:3914:12)
E/flutter (23721): #3      Navigator.of (package:flutter/src/widgets/navigator.dart:2115:19)
E/flutter (23721): #4      _AnimatedSplashState.build.<anonymous closure> (package:fstore/widgets/common/animated_splash.dart:75:23)
E/flutter (23721): #5      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (23721): #6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (23721): #7      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter (23721): #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter (23721): #9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter (23721): #10     Future._complete (dart:async/future_impl.dart:516:7)
E/flutter (23721): #11     new Future.delayed.<anonymous closure> (dart:async/future.dart:315:16)
E/flutter (23721): #12     _rootRun (dart:async/zone.dart:1180:38)
E/flutter (23721): #13     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23721): #14     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (23721): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (23721): #16     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (23721): #17     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23721): #18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (23721): #19     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (23721): #20     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (23721): #21     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (23721): #22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (23721): 
I/flutter (23721): [2020-05-13 16:47:41.859632Z][Fluxstore][AppState] build
I/flutter (23721): [2020-05-13 16:47:41.860343Z][Fluxstore][AppState] build Theme
I/flutter (23721): [2020-05-13 16:47:41.873794Z][Fluxstore][tabbar] ============== tabbar.dart DASHBOARD ==============
I/flutter (23721): [2020-05-13 16:47:41.897836Z][Fluxstore][Home] build
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/flutter/category/cache?categoryIds=
I/flutter (23721): [2020-05-13 16:47:42.131610Z][Fluxstore][wocommerce_api][22:17:42.131532] getAsync START [endPoint:flutter/category/cache?categoryIds=] url:https://unostop.in/wp-json/wc/v2/flutter/category/cache?categoryIds=&consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): 
I/flutter (23721): HandshakeException: Handshake error in client (OS Error: 
I/flutter (23721): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
I/flutter (23721): 
I/flutter (23721): HandshakeException: Handshake error in client (OS Error: 
I/flutter (23721): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
I/flutter (23721): getFilterTags: HandshakeException: Handshake error in client (OS Error: 
I/flutter (23721): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
I/flutter (23721): getFilterAttributes: HandshakeException: Handshake error in client (OS Error: 
I/flutter (23721): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
E/flutter (23721): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (23721): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
E/flutter (23721): 
I/flutter (23721): 
E/flutter (23721): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: HandshakeException: Handshake error in client (OS Error: 
E/flutter (23721): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))
E/flutter (23721): 
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/womensfashion.png.
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/Cakes.png.
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/mensfachion.png.
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
W/IInputConnectionWrapper(23721): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(23721): getTextBeforeCursor on inactive InputConnection
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/Pizza.png.
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
D/DecorView(23721): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@a121626[MainActivity]
D/PhoneWindow(23721): setNavigationBarColor: ff000000
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): Bad state: Failed to load https://unostop.in/wp-content/uploads/2020/05/Grocery.png.
I/flutter (23721): fetchProductsByCategory: products?status=publish&lang=en&per_page=20&page=1&category=92
I/flutter (23721): url https://unostop.in/wp-json/wc/v2/products?status=publish&lang=en&per_page=20&page=1&category=92
I/flutter (23721): [2020-05-13 16:47:52.002563Z][Fluxstore][wocommerce_api][22:17:52.002486] getAsync START [endPoint:products?status=publish&lang=en&per_page=20&page=1&category=92] url:https://unostop.in/wp-json/wc/v2/products?status=publish&lang=en&per_page=20&page=1&category=92&consumer_key=ck_6bdb97681767208a50eecc784e6dda377c610999&consumer_secret=cs_bc8b54286677fcba17f9dd783c67529560743766
I/flutter (23721): screenName null
I/flutter (23721): 0
I/flutter (23721): 
I/flutter (23721): 0
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode
I/chatty  (23721): uid=10443(com.india.unostop) Thread-8 identical 2 lines
I/flutter (23721): NoSuchMethodError: The getter 'statusCode' was called on null.
I/flutter (23721): Receiver: null
I/flutter (23721): Tried calling: statusCode

**Comment by Amitjeypore** [comment]
Please help me, If required I will send my WP credentials so that you can check all the plugins are active,

**Comment by vumanhsn97** [comment]
Please check again.
https://tppr.me/6jxbh
https://tppr.me/h9LAI

**Comment by Amitjeypore** [comment]
Yes for me SSL was the issue, I worked it out and the rest ap started working.
