### ISSUE TITLE
Flux builder error site image

### ISSUE THREAD

**Issue by byroncanga** [inspireui/fluxbuilder#79]
![image](https://user-images.githubusercontent.com/65374818/81996272-3ae6bf80-9612-11ea-9c9c-3359fcfcb83d.png)
![image](https://user-images.githubusercontent.com/65374818/81996287-46d28180-9612-11ea-99de-a1e111dae45b.png)

I'm using the visual Builde but it doesn't work for me to load the images from my site, it keeps thinking and it doesn't load more images

and the image search engine in the photos section of the site does not work eithe

**Comment by minhcasi** [comment]
@byroncanga - could you help to share your config site info so that we could help for checking
