### ISSUE TITLE
VALIDATE SETTINGS

### ISSUE THREAD

**Issue by atwaaar** [inspireui/fluxbuilder#8]
Hello, 
I have an issue when I try to connect fluxbuilder with Opencart 3.0.3.2 it keeps checking Reset API and Image setting at the same time if run the preview mode I can see my product there!

thanks

**Comment by peppyday** [comment]
Yes for me too..

**Comment by peppyday** [comment]
Now its working.....

**Comment by atwaaar** [comment]
what you did and which version you have?

**Comment by peppyday** [comment]
You mean opencart version?

**Comment by peppyday** [comment]
opencart Version 3.0.3.2

**Comment by peppyday** [comment]
and  FluxStore 1.6.6

**Comment by atwaaar** [comment]
oh! so there is a new update for fluxStore today
thanks for helping

**Comment by peppyday** [comment]
Also it works and hangs sometime.. may be server issue.

**Comment by atwaaar** [comment]
still I'm having the same issue even after I upgrade fluxstore to 1.6.6

**Comment by minhcasi** [comment]
@atwaaar - would you mind to take the video of the issues so that we could try to replicate form our development side - thank you!

**Comment by vumanhsn97** [comment]
@atwaaar Please follow this documents: https://docs.inspireui.com/fluxstore/opencart-setup/. Make sure you install Mstore Api

**Comment by minhcasi** [comment]
@atwaaar
