### ISSUE TITLE
blog not working

### ISSUE THREAD

**Issue by miskayapp** [inspireui/fluxbuilder#80]
i bought the fluxstore for woocomerce and folled all the instructions but my blog dont show anything on the app

**Comment by vumanhsn97** [comment]
Make sure you have data in posts https://tppr.me/R2urP

**Comment by miskayapp** [comment]
i have posts on my wordress site,my config

/// Your website woocommerce. You can remove this line if it same url
"blog": "https://www.miskayboutique.com/blog",

**Comment by vumanhsn97** [comment]
Blog url is "blog": "https://www.miskayboutique.com"
Please fix itsec_rest_api_access_restricted: https://www.miskayboutique.com/wp-json/wp/v2/posts    
Solution: https://wordpress.org/support/topic/rest-api-restriction/

**Comment by miskayapp** [comment]
i use itheme on my website, is there any more suggestion to make this app
work better?, and my app loads product very slow like 10secs, i have use
the regeneration plugin and uploaded the config file to mstoreapi but its
still not fast

**Comment by miskayapp** [comment]
blog fixed, my apple login does not work, i get this error message,
"warning: there is an issue with the app during request the data, please
contact admin for fixing the isues DatabaseError(1,com.firebase, Permission
Denied)"

**Comment by vaibhav891** [comment]
Facing same issue. Did we find a solution to this?

**Comment by tskmark** [comment]
No, i just removed Apple login.

**Comment by vaibhav891** [comment]
Were you able to publish on AppStore then? I believe without sign in with
apple, apps are not allowed on Appstore.

**Comment by tskmark** [comment]
Not sure about that my app was published but apple sign in still not working
