### ISSUE TITLE
FLUX BUILDER UNABLE TO INSTALL ERROR-0xc000007b error

### ISSUE THREAD

**Issue by Shadowji** [inspireui/fluxbuilder#82]
HI I AM UNABLE TO INSTALL FLUXBUILDER SOFTWARE I FIXED THE VCRUNTIME140_1.DLL EROOR BUT AFTER THAT I ENCOUNTERED NEW ERROR 0xc000007b "THE APPLICATION WAS UNABLE TO START CORRECTLY"

**Comment by minhcasi** [comment]
@Shadowji - pls try to install https://github.com/inspireui/fluxbuilder/releases/download/1.0.0/vc_redist.x64.exe and restart the window to fix this issue

**Comment by Shadowji** [comment]
tried to install vc_redist.x64 but the setup is failed error 0x80070666

**Comment by minhcasi** [comment]
@Shadowji - could you the solution on this ticket https://github.com/inspireui/fluxbuilder/issues/4

**Comment by Shadowji** [comment]
Hi I have tried the solutions no luck

**Comment by minhcasi** [comment]
@Shadowji - would you mind sharing the screenshot so that i can forward to my team for investigating. Also note what is the Window OS you are using - thank you!

**Comment by Shadowji** [comment]
![Screenshot_2020-05-22-12-39-43-12](https://user-images.githubusercontent.com/65677660/82663714-d77e1280-9c4d-11ea-953a-987db2a105ad.png)
![Screenshot_2020-05-22-12-40-01-63](https://user-images.githubusercontent.com/65677660/82663729-dcdb5d00-9c4d-11ea-9d45-d9b014fa71bd.png)

**Comment by Shadowji** [comment]
I hope you guys will find a solution to it because I am facing a delay here.

**Comment by Shadowji** [comment]
Do you have any option to build this app online ?
Because I am loosing my time here

**Comment by minhcasi** [comment]
@Shadowji - we will investigate and also release the web version

**Comment by vumanhsn97** [comment]
@Shadowji 
Please download latest version: https://github.com/inspireui/fluxbuilder/releases
