### ISSUE TITLE
The Image Cache not not installed

### ISSUE THREAD

**Issue by onurkendir** [inspireui/fluxbuilder#83]
I installed the FluxBuilder application on my computer. I installed the Regenerate Thumbnails plugin on our Wordpress website. Flutter and Android studio everything works properly. When I enter the website name in FluxBuilder application, The Image Cache not not installed error. However, Regenerate Thumbnails plugin is installed on our website and I have done all the steps written in the documentation correctly. Do I see this error because I have not yet purchased the FluxNews app, or is there any other problem?

**Comment by minhcasi** [comment]
@onurkendir - we will investigate this issue and let you know - could you share your website config file to http://private.inspireui.com/ - thank you!

**Comment by minhcasi** [comment]
I'm sorry to close this ticket as there is no response, please help to create a new one and link to this ticket if the problem is not solved - thank you for your time!
