### ISSUE TITLE
Website Data Option

### ISSUE THREAD

**Issue by MorisTech** [inspireui/fluxbuilder#86]
Hello
I can't find the import Website Data option after connecting the REST API with the Fluxbuilder

**Comment by minhcasi** [comment]
@MorisTech - pls help to check this guide https://docs.inspireui.com/fluxbuilder

**Comment by MorisTech** [comment]
Okay now I don't understand anything, after installing MCFM plugin market place and connecting the REST API to the app, the App doesn't show list of vendors from the website, it doesn't show in stores

**Comment by MorisTech** [comment]
?????

**Comment by minhcasi** [comment]
Thank you for the feedback.

Please help us to submit this form and fill all required info to continue with the support  - http://private.inspireui.com/ - please don't share the purchase code or screenshot public here as another user will use it for activation.

We will close this ticket in 24 hours if it is not provided enough detail, kindly reopen the ticket after you have done the form submission. Thank you for your time!

**Comment by MorisTech** [comment]
Hello, I made a private request, nothing yet from you guys, what's the problem, even sent you a private email, you read but didn't reply, this thing is frustrating

**Comment by minhcasi** [comment]
@MorisTech - we got your submission - but the config is using the default demo website, it is not using our config file so that we could not help for checking - could you able to share the screenshot issue?

**Comment by MorisTech** [comment]
Should I change the Config to my website or send a screenshot, or what do you need?

**Comment by MorisTech** [comment]
I've changed the config to my website's details and changed the currency and all
What next?

Should I try to run in Android Studio, the Fluxbuilder doesn't show The Stores

**Comment by MorisTech** [comment]
I've changed the config to my website's details and changed the currency and all
What next?

Should I try to run in Android Studio, the Fluxbuilder doesn't show The Stores

**Comment by MorisTech** [comment]
I've changed the config to my website's details and changed the currency and all
What next?

Should I try to run in Android Studio, the Fluxbuilder doesn't show The Stores

**Comment by MorisTech** [comment]
I'm getting this error after inputting my website's data

> Install Android SDK Platform 28 (revision: 6)" complete.
> "Install Android SDK Platform 28 (revision: 6)" finished.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':notification_permissions:compileDebugAidl'.
> > Could not resolve all dependencies for configuration ':notification_permissions:debugRuntimeClasspath'.
>    > Could not determine artifacts for androidx.core:core:1.0.1
>       > Could not get resource 'https://dl.google.com/dl/android/maven2/androidx/core/core/1.0.1/core-1.0.1.aar'.
>          > Could not HEAD 'https://dl.google.com/dl/android/maven2/androidx/core/core/1.0.1/core-1.0.1.aar'.
>             > Remote host closed connection during handshake
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1h 0m 8s
> The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
> Building plugin app_settings...
> Running Gradle task 'assembleAarRelease'...
> Downloading https://services.gradle.org/distributions/gradle-6.2.2-all.zip
> 
> 
> Exception in thread "main" java.net.SocketException: Connection reset
> 	at java.net.SocketInputStream.read(SocketInputStream.java:210)
> 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
> 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
> 	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
> 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
> 	at org.gradle.wrapper.Download.downloadInternal(Download.java:66)
> 	at org.gradle.wrapper.Download.download(Download.java:51)
> 	at org.gradle.wrapper.Install$1.call(Install.java:62)
> 	at org.gradle.wrapper.Install$1.call(Install.java:48)
> 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
> 	at org.gradle.wrapper.Install.createDist(Install.java:48)
> 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
> 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
> 
> Finished with error: The plugin app_settings could not be built due to the issue above.
>

**Comment by minhcasi** [comment]
@MorisTech - try to double-check your flutter sdk by using this guide - https://docs.inspireui.com/fluxstore/woocommerce-setup/ 

And video
https://www.youtube.com/watch?v=3dv_8UerNpQ
https://www.youtube.com/watch?v=ReAUZDIgh2I

**Comment by MorisTech** [comment]
Did that

now I'm getting this errors



> Launching lib\main.dart on AOSP on IA Emulator in debug mode...
> Running Gradle task 'assembleDebug'...
> 
> Compiler message:
> lib/common/styles.dart:52:9: Error: No named parameter with the name 'headline6'.
>         headline6: TextStyle(
>         ^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart:109:9: Context: Found this candidate, but the arguments don't match.
>   const TextTheme({
>         ^^^^^^^^^
> lib/common/styles.dart:68:25: Error: The getter 'headline5' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline5'.
>         headline5: base.headline5
>                         ^^^^^^^^^
> lib/common/styles.dart:70:25: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
>         headline6: base.headline6.copyWith(fontSize: 18.0),
>                         ^^^^^^^^^
> lib/common/styles.dart:75:25: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>         subtitle1: base.subtitle1.copyWith(
>                         ^^^^^^^^^
> lib/common/styles.dart:68:9: Error: No named parameter with the name 'headline5'.
>         headline5: base.headline5
>         ^^^^^^^^^
> lib/common/styles.dart:88:49: Error: The getter 'headline4' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline4'.
>       .copyWith(headline4: kHeadlineTheme(base).headline4.copyWith());
>                                                 ^^^^^^^^^
> lib/common/styles.dart:88:17: Error: No named parameter with the name 'headline4'.
>       .copyWith(headline4: kHeadlineTheme(base).headline4.copyWith());
>                 ^^^^^^^^^
> lib/common/styles.dart:133:9: Error: No named parameter with the name 'headline6'.
>         headline6: TextStyle(
>         ^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart:109:9: Context: Found this candidate, but the arguments don't match.
>   const TextTheme({
>         ^^^^^^^^^
> lib/screens/settings/wishlist.dart:232:44: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                                           .subtitle1
>                                            ^^^^^^^^^
> lib/screens/blogs/post_screen.dart:134:48: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>         textStyle: Theme.of(context).textTheme.subtitle1.copyWith(
>                                                ^^^^^^^^^
> lib/widgets/blog/slider_list.dart:214:40: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
>                                       .bodyText1
>                                        ^^^^^^^^^
> lib/widgets/blog/slider_list.dart:227:40: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
>                                       .bodyText1
>                                        ^^^^^^^^^
> lib/widgets/blog/slider_list.dart:330:40: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
>                                       .bodyText1
>                                        ^^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.3-dev/lib/src/gesture/extended_image_slide_page_route.dart:335:9: Error: No named parameter with the name 'primaryRouteAnimation'.
>         primaryRouteAnimation: animation,
>         ^^^^^^^^^^^^^^^^^^^^^
> /C:/src/flutter/packages/flutter/lib/src/cupertino/route.dart:430:3: Context: Found this candidate, but the arguments don't match.
>   CupertinoFullscreenDialogTransition({
>   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> lib/screens/checkout/payment.dart:222:58: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                       style: Theme.of(context).textTheme.subtitle1.copyWith(
>                                                          ^^^^^^^^^
> lib/screens/checkout/review.dart:66:56: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                     style: Theme.of(context).textTheme.subtitle1.copyWith(
>                                                        ^^^^^^^^^
> lib/screens/checkout/review.dart:92:62: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                           style: Theme.of(context).textTheme.subtitle1.copyWith(
>                                                              ^^^^^^^^^
> lib/screens/checkout/review.dart:118:58: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                       style: Theme.of(context).textTheme.subtitle1.copyWith(
>                                                          ^^^^^^^^^
> lib/screens/checkout/review.dart:143:56: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                     style: Theme.of(context).textTheme.subtitle1.copyWith(
>                                                        ^^^^^^^^^
> lib/widgets/backdrop/backdrop.dart:95:39: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
>           Theme.of(context).textTheme.headline6.copyWith(color: Colors.white),
>                                       ^^^^^^^^^
> lib/screens/users/user_point.dart:69:60: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                         style: Theme.of(context).textTheme.subtitle1.copyWith(
>                                                            ^^^^^^^^^
> lib/screens/users/user_point.dart:102:38: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                                     .subtitle1
>                                      ^^^^^^^^^
> lib/vendor/store_detail/store_detail_screen.dart:96:30: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
>                             .headline6
>                              ^^^^^^^^^
> lib/vendor/store/widgets/store_item.dart:111:30: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                             .subtitle1
>                              ^^^^^^^^^
> lib/widgets/product/product_card_view.dart:179:56: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
>                     style: Theme.of(context).textTheme.headline6.copyWith(
>                                                        ^^^^^^^^^
> lib/widgets/product/product_card_view.dart:191:58: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
>                       style: Theme.of(context).textTheme.headline6.copyWith(
>                                                          ^^^^^^^^^
> lib/widgets/product/product_list_tile.dart:150:54: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
>                   style: Theme.of(context).textTheme.headline6.copyWith(
>                                                      ^^^^^^^^^
> lib/widgets/product/product_list_tile.dart:159:56: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
>                     style: Theme.of(context).textTheme.headline6.copyWith(
>                                                        ^^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
>                 onRatingChanged: (rating) {
>                 ^^^^^^^^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
>   SmoothStarRating({
>   ^^^^^^^^^^^^^^^^
> lib/vendor/store_detail/widgets/contact.dart:108:59: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                 style: Theme.of(context).primaryTextTheme.subtitle1.copyWith(
>                                                           ^^^^^^^^^
> lib/widgets/blog/detailed_blog/detailed_blog_fullsize_image.dart:146:59: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
>                               Theme.of(context).textTheme.bodyText1.copyWith(
>                                                           ^^^^^^^^^
> lib/widgets/blog/detailed_blog/detailed_blog_quarter_image.dart:153:59: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
>                               Theme.of(context).textTheme.bodyText1.copyWith(
>                                                           ^^^^^^^^^
> lib/screens/cart/my_cart.dart:152:65: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                                     style: localTheme.textTheme.subtitle1
>                                                                 ^^^^^^^^^
> lib/widgets/blog/detailed_blog_fullsize_image.dart:214:59: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
>                               Theme.of(context).textTheme.bodyText1.copyWith(
>                                                           ^^^^^^^^^
> lib/widgets/blog/detailed_blog_half_image.dart:211:38: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
>                                     .bodyText1
>                                      ^^^^^^^^^
> lib/widgets/blog/detailed_blog_quarter_image.dart:206:32: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
>                               .bodyText1
>                                ^^^^^^^^^
> lib/widgets/blog/detailed_blog_view.dart:114:57: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
>                             Theme.of(context).textTheme.bodyText1.copyWith(
>                                                         ^^^^^^^^^
> lib/widgets/home/search/custom_search_page.dart:456:38: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>               style: theme.textTheme.subtitle1,
>                                      ^^^^^^^^^
> lib/screens/detail/product_title.dart:66:50: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>               style: Theme.of(context).textTheme.subtitle1.copyWith(
>                                                  ^^^^^^^^^
> lib/screens/detail/product_title.dart:80:58: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                       style: Theme.of(context).textTheme.subtitle1.copyWith(
>                                                          ^^^^^^^^^
> lib/screens/detail/product_title.dart:117:52: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>                 style: Theme.of(context).textTheme.subtitle1.copyWith(
>                                                    ^^^^^^^^^
> lib/vendor/chat/messages.dart:152:40: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
>                 style: theme.textTheme.headline6.copyWith(
>                                        ^^^^^^^^^
> lib/vendor/chat/messages.dart:235:42: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
>                   style: theme.textTheme.headline6.copyWith(
>                                          ^^^^^^^^^
> lib/services/helper/flash_helper.dart:56:66: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
>     return (theme.dialogTheme?.titleTextStyle ?? theme.textTheme.subtitle1)
>                                                                  ^^^^^^^^^
> lib/services/helper/flash_helper.dart:62:68: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.
>  - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/C:/src/flutter/packages/flutter/lib/src/material/text_theme.dart').
> Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText1'.
>     return (theme.dialogTheme?.contentTextStyle ?? theme.textTheme.bodyText1)
>                                                                    ^^^^^^^^^
> Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> build failed.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildDebug'.
> > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4m 55s
> Finished with error: Gradle task assembleDebug failed with exit code 1
>

**Comment by MorisTech** [comment]
And again, I followed the steps to install flutter, I'm not sure anything is wrong with it

**Comment by MorisTech** [comment]
![flutter](https://user-images.githubusercontent.com/31305956/82998102-31d8f380-9fff-11ea-952e-905b3f6ecb4a.PNG)
This is my cmd when I run flutter

**Comment by minhcasi** [comment]
@MorisTech your flutter SDK is out-date pls try this script

```
flutter channel stable
flutter upgrade --force
```

**Comment by MorisTech** [comment]
Okay, I did that

this is the error I'm getting now

> Downloading android-x64-profile/windows-x64 tools...                6.9s
> Downloading android-x64-release/windows-x64 tools...                4.5s
> Running "flutter pub get" in source...                             63.0s
> Launching lib\main.dart on AOSP on IA Emulator in debug mode...
> Running Gradle task 'assembleDebug'...
> 
> Compiler message:
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
>                 onRatingChanged: (rating) {
>                 ^^^^^^^^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
>   SmoothStarRating({
>   ^^^^^^^^^^^^^^^^
> 
> Compiler message:
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/rate_my_app-0.6.0+2/lib/src/dialogs.dart:272:17: Error: No named parameter with the name 'onRatingChanged'.
>                 onRatingChanged: (rating) {
>                 ^^^^^^^^^^^^^^^
> /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.1/lib/smooth_star_rating.dart:24:3: Context: Found this candidate, but the arguments don't match.
>   SmoothStarRating({
>   ^^^^^^^^^^^^^^^^
> Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
> build failed.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882
> 
> * What went wrong:
> Execution failed for task ':app:compileFlutterBuildDebug'.
> > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 11m 56s
> Exception: Gradle task assembleDebug failed with exit code 1
>

**Comment by MorisTech** [comment]
??

**Comment by MorisTech** [comment]
I fixed it, I changed rate_my_app to 0.6.0+3 or something like that

**Comment by MorisTech** [comment]
Okay now the app works, but the products doesn't display, only one does
also when I want to checkout i log in with my details but it takes me back to the cart and when I click checkout again it takes me to the login page

**Comment by minhcasi** [comment]
moved to https://github.com/inspireui/support/issues/3494
