### ISSUE TITLE
uploading to appstore

### ISSUE THREAD

**Issue by miskayapp** [inspireui/fluxbuilder#87]
i keep getting this error, while i try to upload the app, "This bundle is invalid - The Info.plist file is missing or could not be parsed"

**Comment by miskayapp** [comment]
![Screen Shot 2020-05-24 at 11 21 35 PM](https://user-images.githubusercontent.com/64660378/82766253-6be6a180-9e15-11ea-826a-2f1e5a494964.png)

**Comment by minhcasi** [comment]
@miskayapp - pls try to update the bundle ID - https://docs.inspireui.com/fluxstore/delivery/#12-change-the-app-bundle-id-package-name - The correct format: com.your-host-name.your-app-name

Read this more detail: https://developer.apple.com/documentation/appstoreconnectapi/bundle_ids

Please help to create your one ticket, instead of posting multi tickets - thank you!

**Comment by miskayapp** [comment]
I HAVE CHANGED THE BUNDLE ID, SAME ERROR

**Comment by miskayapp** [comment]
i have changed everything , must the hostNAME BE A REAL WEBSITE DOMAIN, I DONT UNDERSTAND

COM.MISKAYBOUT.MISKAY IS WHAT I USED, MY WEBSITE URL IS MISKAYBOUTIQUE.COM, I TRIED THAT FOR THE BUNDDLE  ID AND AND MY APPLE DEVELOPER ACCOUNT DIDNT ACCEPT

**Comment by miskayapp** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleDisplayName</key>
	<string>miskay</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>miskay</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>miskaybout.com</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>Miskay</string>
				<string>fb430258564493822</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.117181301928-ctli4epssdmkshg0tg8oa9smlt5udnub</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>
	<key>FacebookAppID</key>
	<string>430258564493822</string>
	<key>FacebookDisplayName</key>
	<string>Miskay</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
	<key>GADApplicationIdentifier</key>
	<string>ca-app-pub-7432665165146018~2664444130</string>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>itms</string>
	</array>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
		<key>NSAllowsArbitraryLoadsInWebContent</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>This app requires access to take the photo from camera</string>
	<key>NSLocationAlwaysUsageDescription</key>
	<string>Need current location access</string>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Get your current location for delivery</string>
	<key>NSMicrophoneUsageDescription</key>
	<string>This app requires</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This app requires access to the photo library to support Chat Features.</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>io.flutter.embedded_views_preview</key>
	<string>YES</string>
</dict>
</plist>
`

my info.plist file

**Comment by miskayapp** [comment]
i have done this bundle id countess times, im getting the same error;

**Comment by miskayapp** [comment]
![Screen Shot 2020-05-26 at 7 39 54 AM](https://user-images.githubusercontent.com/64660378/82868223-2a90e780-9f24-11ea-8014-b212ec3fff0d.png)
