### ISSUE TITLE
bitcode error

### ISSUE THREAD

**Issue by miskayapp** [inspireui/fluxbuilder#88]
i get this error archiving on xcode 

bitcode bundle could not be generated because '/Users/mac/Desktop/miskayF/ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/mac/Desktop/miskayF/ios/Flutter/Flutter.framework/Flutter' for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by minhcasi** [comment]
<img width="1091" alt="Screen Shot 2020-05-25 at 08 55 52" src="https://user-images.githubusercontent.com/1459805/82771239-8a748900-9e65-11ea-8046-52b45837aa15.png">
Try to edit ios/Podfile and enable Bitcode to fix this issue

Please help to create your one ticket, instead of posting multi tickets - thank you!

**Comment by miskayapp** [comment]
its enabled already and set to yes, its not multiple tickets, this is from the current version of the app and the other was from the previous version

**Comment by miskayapp** [comment]
its still giving the same error

**Comment by miskayapp** [comment]
config.build_settings['ENABLE_BITCODE'] = 'YES' 

the word bitcode is underlined on my ide, like there is something wrong

**Comment by miskayapp** [comment]
is there any file i can upload here, i really need help

**Comment by miskayapp** [comment]
hello

**Comment by miskayapp** [comment]
Showing All Messages
Bitcode bundle could not be generated because '/Users/mac/Desktop/miskay/ios/Flutter/Flutter.framework/Flutter' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Users/mac/Desktop/miskay/ios/Flutter/Flutter.framework/Flutter' for architecture armv7

**Comment by miskayapp** [comment]
[Build target webview_flutter_2020-05-27T00-54-07.txt](https://github.com/inspireui/fluxbuilder/files/4685687/Build.target.webview_flutter_2020-05-27T00-54-07.txt)
