### ISSUE TITLE
Archiving app error

### ISSUE THREAD

**Issue by miskayapp** [inspireui/fluxbuilder#89]
![Screen Shot 2020-05-24 at 10 54 32 PM](https://user-images.githubusercontent.com/64660378/82765794-b2d29800-9e11-11ea-9d9f-b439d835f231.png)
please please help me out, I get this error while I try to archive the app, I am 2 days behind sending a copy to client for testing.

**Comment by minhcasi** [comment]
Hi man, pls check solution on #88 - the same ticket root cause

**Comment by miskayapp** [comment]
![Screen Shot 2020-05-26 at 11 47 56 PM](https://user-images.githubusercontent.com/64660378/82957686-85215680-9fab-11ea-9b16-150ba43510c7.png)
same error
