### ISSUE TITLE
Shipping Methods not loading in FluxBuilder

### ISSUE THREAD

**Issue by eduardn1** [inspireui/fluxbuilder#9]
Hi there, recently buyed FluxStore Woocommerce and now i see that you created this lovely visual builder :) so i will give it try. 

After i connected to my api woocommerce website, shipping methods doesn't load. Any ideas ? 

can we manage to change language and text directly from the builder ? or what files do we have to edit for the languages ? thx 

https://prnt.sc/rs7so0
https://prnt.sc/rs7tei

**Comment by minhcasi** [comment]
@eduardn1 - thank you for the feedback, could I know if you are using the default shipping from WooCommerce?

We will add some option to switch the language features on next coming version

**Comment by eduardn1** [comment]
> @eduardn1 - thank you for the feedback, could I know if you are using the default shipping from WooCommerce?
> 
> We will add some option to switch the language features on next coming version

Hi there Minhcasi, i have Weight Base Shipping Methods in the default Shipping

**Comment by vumanhsn97** [comment]
@eduardn1 Sorry, our products just support default shipping in WooCommerce plugin

**Comment by minhcasi** [comment]
@eduardn1 - please help to create new Request Feature for the Weight Base Shipping to https://github.com/inspireui/support/issues - we will preview and consider it upgrade it later on Fluxstore app 😊
