### ISSUE TITLE
Size button - Terms and con - Menu and category bar issues

### ISSUE THREAD

**Issue by mitovos** [inspireui/fluxbuilder#91]
Hi,

Thank you for your last update, it is good to see different options, but i have found too many issues with this one and if you could repair this, that would be great! On the first picture- i am having issues with the size button because it doesn't show the button it only shows the quantity! The second photo shows terms and conditions could you kindly let me know if i can upload my own one or is the terms and conditions automatically integrated on the web? And the third photo shows an issue with the menu at the profile where it is impossible for me to change the logo and some stuff because there is no save button shown? And the final photo could you kindly create an option to disable category main bar category names etc. Thank you so much for the beautiful updates i really appreciate it! 

![1](https://user-images.githubusercontent.com/65925202/82845245-afa3de80-9edb-11ea-8621-965708a81143.png)
![2](https://user-images.githubusercontent.com/65925202/82845247-b29ecf00-9edb-11ea-8317-313d47e8b816.png)
![3](https://user-images.githubusercontent.com/65925202/82845248-b3376580-9edb-11ea-9536-f8782b906eff.png)
![4](https://user-images.githubusercontent.com/65925202/82845249-b3376580-9edb-11ea-98d5-8e13232e6be6.png)

**Comment by minhcasi** [comment]
@mitovos - thank you for the suggestion, we will investigate and keep an update :)

**Comment by mitovos** [comment]
Thank You Mate, also on more thing if you can do it it can be great for a dark theme to make the option to upload dark logo as well because you know most of the logos they are (transparent .png) or black logos when you press dark theme it's impossible to see it.

Thank you so much for taking on board these things!

**Comment by iqmtgar** [comment]
mitovos  
minhcasi
Hello how are you
Can you help me put a word under its icon "home"

**Comment by vumanhsn97** [comment]
@iqmtgar 
In your config_xx.json add your label in item of tabbar https://tppr.me/B0ZQ8

**Comment by iqmtgar** [comment]
@vumanhsn97 
thanks thanks very much
You are a good man
I apologize if bothering you I have another quick question
How do I make a default language for the application config_ar.json?
i want default  language  arabic not english
If you can not help me, thank you
I appreciate it ^_^

**Comment by iqmtgar** [comment]
very thank you bro ^_^

**Comment by mitovos** [comment]
Hi, 

Can you please review your update at APP Store it's impossible to update or it's not released yet 
Thanks,

![Screen Shot 2020-06-23 at 13 22 56](https://user-images.githubusercontent.com/65925202/85403099-b9f5de80-b554-11ea-9ec8-02a5f7c2a7c1.png)

![Screen Shot 2020-06-23 at 13 05 05](https://user-images.githubusercontent.com/65925202/85402802-35a35b80-b554-11ea-8784-570e06897ce5.png)
