### ISSUE TITLE
ad hoc upload

### ISSUE THREAD

**Issue by miskayapp** [inspireui/fluxbuilder#92]
i try to upload and when i select ad-hoc, i get this error.
![Screen Shot 2020-05-26 at 8 09 40 AM](https://user-images.githubusercontent.com/64660378/82870752-63cb5680-9f28-11ea-98c4-fe01ad963eed.png)

**Comment by minhcasi** [comment]
@miskayapp - did you try to run `flutter release ios` ?

**Comment by miskayapp** [comment]
no

**Comment by miskayapp** [comment]
no

**Comment by minhcasi** [comment]
@miskayapp - try to read this guide carefully pls - https://docs.inspireui.com/fluxstore/delivery/
