### ISSUE TITLE
Fluxbuilder error, images and translation

### ISSUE THREAD

**Issue by Marcleiton** [inspireui/fluxbuilder#93]
Hello, I have some bugs to report.

1°  I also have this image error fluxbuilder https://i.imgur.com/AftIizb.png

2 ° Some bugs in the fluxbuilder after installing the WPML plugin, and it is not possible to change the language in the fluxbuilder.
https://imgur.com/a/SQQZnFk

3° In addition when I select another language for example Brazil the fluxbuilder does not change the language.

**Comment by vumanhsn97** [comment]
@Marcleiton 
Please download latest version: https://github.com/inspireui/fluxbuilder/releases

**Comment by Marcleiton** [comment]
Hello, I continue with the same error, when I change the language by the fluxbuilder to launch the code the same does not change, I go on publishing and it always remains the same code in English, and not in the desired language.

Some way to solve this, because whenever I open the app it is in the language I don't want, since the code has been changed to the default language and when you put the code in the fluxstore it is always in English.
