### ISSUE TITLE
Not receiving activation link after registration

### ISSUE THREAD

**Issue by naheedakhtar** [inspireui/fluxbuilder#96]
This is with respect to fluxbuilder app. I have downloaded fluxbuilder v1.05 and as per the guide & have tried to register using email xxx@abc.com (same email which i use for envato / codecanyon).

I received message that activation link will be sent to my email  - however I didn't receive any such link.

please advise.

**Comment by minhcasi** [comment]
@naheedakhtar - would you mind to share the screenshot of the issue - thank you!

**Comment by naheedakhtar** [comment]
![fluxbuilder](https://user-images.githubusercontent.com/1256701/83228461-0e44b300-a18f-11ea-83ba-8a2ad22fc705.JPG)

**Comment by naheedakhtar** [comment]
It says that we need to click on activation link which has been sent on email before logging ...however i m not receiving any email of activation link


Regards

**Comment by Haniel5** [comment]
Hi @minhcasi please help to consider to activate his email sales@technologymaze.com from the backend, because he can not receive both activation and reset password emails. Thank you for your help

**Comment by naheedakhtar** [comment]
Please help...still waiting

**Comment by minhcasi** [comment]
@naheedakhtar - we could not reproduce this issue, the active email still work well, please help to test with other Email address
