### ISSUE TITLE
Devices not connected error in android studio and visual studio code& Rest API error while setting up Flux builder

### ISSUE THREAD

**Issue by Surendrareddyputlur** [inspireui/fluxbuilder#97]
Devices not connected error in coming when we run flutter doctor in android studio and visual studio code

& Rest API error while setting up Flux builder pro.

Please help us on above.

Thank you.

**Comment by minhcasi** [comment]
@Surendrareddyputlur - could you share more screenshot issue - thank you!

**Comment by Surendrareddyputlur** [comment]
> @Surendrareddyputlur - could you share more screenshot issue - thank you!

Please find the screen shot pls.
![For Github](https://user-images.githubusercontent.com/66058197/83252344-b0cd5800-a1c8-11ea-8aeb-190c95ffd4bd.PNG)

**Comment by minhcasi** [comment]
@Surendrareddyputlur - this topic will be related to the product from Fluxstore - pls raise the issue to https://github.com/inspireui/support/issues
